//! Queue-memory backpressure from the output side back to the Read step.
//!
//! The threaded BAM pipeline advertises a queue memory budget (`--max-memory`,
//! logged as "Queue memory budget: N total"). Every stage between Read and
//! Write is bounded, but the bound on most of them is a *slot count*, not a
//! byte count — so when the output device stalls, each stage saturates with
//! however many bytes its slots happen to hold and the budget is not what
//! decides the ceiling.
//!
//! Read is the pipeline's only source of new bytes, and nothing downstream
//! waits on it to make progress, so gating Read on the accounted in-flight
//! bytes bounds the whole pipeline without risking deadlock. These tests pin
//! that behaviour: with a writer that never completes, the pipeline must stop
//! pulling input rather than draining the whole file into its queues.
//!
//! See <https://github.com/fulcrumgenomics/fgumi/issues/746>.

#![allow(clippy::cast_possible_truncation)]

use noodles::bam;
use noodles::sam::Header;
use noodles::sam::alignment::RecordBuf;
use noodles::sam::alignment::io::Write as AlignmentWrite;
use std::io::{self, Read, Write};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};

use crate::helpers::bam_generator::{create_minimal_header, create_umi_family, to_record_buf};
use fgumi_lib::grouper::SingleRecordGrouper;
use fgumi_lib::read_info::LibraryIndex;
use fgumi_lib::unified_pipeline::{
    GroupKeyConfig, PipelineConfig, PipelineFunctions, run_bam_pipeline, serialize_bam_record_into,
};

/// Queue memory budget used by the tests, in bytes.
const TEST_BUDGET_BYTES: u64 = 2 * 1024 * 1024;

/// UMI families in the test input, and reads per family.
///
/// Sized so the *compressed* input is several times `TEST_BUDGET_BYTES`. That
/// margin matters in compressed terms specifically: Q1 holds raw BGZF blocks,
/// so if the whole compressed file fits under the budget the reader parks it
/// all in Q1 before any stage downstream builds up and the gate never engages —
/// a smaller input would be swallowed whole and the assertions would prove
/// nothing. The generated bytes are built once and shared (see
/// [`shared_bam_bytes`]) so the tests do not each pay to regenerate them.
///
/// The count is also chosen for *read-ahead* headroom, not just "exceeds the
/// budget". The reader stops once its accounted in-flight bytes reach the
/// budget, and that stopping point — the compressed bytes consumed — is roughly
/// `budget + queue/batch overhead`, essentially independent of the input size.
/// The margin assertions require the reader to leave at least one whole
/// `TEST_BUDGET_BYTES` unread, so the fixture has to clear
/// `read_ahead + TEST_BUDGET_BYTES` by a comfortable margin. At this size the
/// compressed input is roughly `MIN_INPUT_HEADROOM_BUDGETS` budgets, which
/// leaves the reader stopping short by more than one extra budget — headroom
/// that a future toolchain/dependency change to BGZF block sizing (which shifts
/// the read-ahead point) cannot erase without a very large drift. Sizing it
/// this way, rather than by a fraction of the input, is what hardens the tests
/// against that drift (issue #789).
///
/// `DEPTH` is 1 because the reads within a family are identical but for their
/// names, so extra depth barely grows the *compressed* size while it multiplies
/// the records written when the fixture is built. One unique read per family
/// gives the needed compressed margin for the least build cost; the pipeline is
/// exercised with a pass-through grouper, so family structure is immaterial
/// here.
const FAMILIES: usize = 175_000;
const DEPTH: usize = 1;

/// The compressed fixture must be at least this many `TEST_BUDGET_BYTES` in
/// size for the read-ahead margin assertions to carry drift headroom.
///
/// The reader's stopping point sits near `budget + overhead` (~1.5 budgets),
/// and the margin assertions demand one further budget left unread, so anything
/// below three budgets has no slack for BGZF block-size drift (issue #789). The
/// precondition in [`stalled_writer_stops_the_reader_within_the_queue_memory_budget`]
/// enforces this so a future shrink of `FAMILIES` fails loudly here rather than
/// silently reintroducing a thin margin.
const MIN_INPUT_HEADROOM_BUDGETS: u64 = 3;

/// The generated BAM input and the header it was built with, materialized once
/// and shared by every test.
///
/// Building the fixture dominates each test's runtime, and all three want the
/// same bytes, so this amortizes it across the suite. Tests clone the byte
/// vector when the pipeline needs to own it.
fn shared_bam_bytes() -> &'static (Header, Vec<u8>) {
    static FIXTURE: OnceLock<(Header, Vec<u8>)> = OnceLock::new();
    FIXTURE.get_or_init(|| {
        let header = create_minimal_header("chr1", 100_000);
        let bytes = build_bam_bytes(&header, FAMILIES, DEPTH);
        (header, bytes)
    })
}

/// A reader that records how many bytes the pipeline has pulled from the input.
struct CountingReader {
    inner: io::Cursor<Vec<u8>>,
    consumed: Arc<AtomicU64>,
}

impl Read for CountingReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let n = self.inner.read(buf)?;
        self.consumed.fetch_add(n as u64, Ordering::Relaxed);
        Ok(n)
    }
}

/// A writer that blocks every write until it is released, then keeps the bytes.
///
/// Stands in for a saturated output device: the pipeline stays healthy (no
/// error, no panic) but makes no write progress at all. Retaining what it
/// eventually accepts lets the recovery test check record identity rather than
/// just a record count.
struct StalledWriter {
    released: Arc<AtomicBool>,
    sink: Arc<Mutex<Vec<u8>>>,
}

impl Write for StalledWriter {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        // Generous enough never to fire in a passing run; bounded so a failed
        // assertion that unwinds before `released.store(true)` does not leave
        // this thread spinning for the rest of the test binary under
        // `cargo test` (where all tests share one process).
        let deadline = Instant::now() + Duration::from_secs(300);
        while !self.released.load(Ordering::Acquire) {
            if Instant::now() >= deadline {
                return Err(io::Error::new(
                    io::ErrorKind::TimedOut,
                    "StalledWriter was never released",
                ));
            }
            std::thread::sleep(Duration::from_millis(5));
        }
        self.sink.lock().expect("sink mutex should not be poisoned").extend_from_slice(buf);
        Ok(buf.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Serialize `header` as a BAM header stream, the way the pipeline's own entry
/// points do before handing the raw writer to `run_bam_pipeline`.
///
/// `run_bam_pipeline` emits record blocks only, so a captured output stream has
/// to be prefixed with this to be readable as a BAM.
fn bam_header_bytes(header: &Header) -> Vec<u8> {
    let mut writer = bam::io::Writer::new(Vec::new());
    writer.write_header(header).expect("write header");
    let mut bgzf = writer.into_inner();
    bgzf.try_finish().expect("finish header BGZF stream");
    bgzf.into_inner()
}

/// Read the record names out of a BAM byte stream, in order.
fn record_names(bam_bytes: &[u8]) -> Vec<String> {
    let mut reader = bam::io::Reader::new(io::Cursor::new(bam_bytes));
    let header = reader.read_header().expect("read header");
    reader
        .record_bufs(&header)
        .map(|r| {
            let record = r.expect("read record");
            String::from_utf8_lossy(record.name().expect("record should have a name").as_ref())
                .into_owned()
        })
        .collect()
}

/// Build a BAM whose compressed size comfortably exceeds the test budget, so a
/// pipeline that respects the budget cannot swallow all of it.
///
/// Written through a temp file rather than an in-memory buffer so the BGZF
/// stream is finalized exactly the way a real input is.
fn build_bam_bytes(header: &Header, num_families: usize, depth: usize) -> Vec<u8> {
    let bases = [b'A', b'C', b'G', b'T'];
    let dir = tempfile::tempdir().expect("temp dir");
    let path = dir.path().join("input.bam");
    {
        let mut writer =
            bam::io::Writer::new(std::fs::File::create(&path).expect("create temp BAM"));
        writer.write_header(header).expect("write header");
        for i in 0..num_families {
            // Vary both the UMI and the sequence so BGZF cannot collapse the
            // file to a handful of blocks; the queues must hold real bytes.
            let umi: String = (0..8).map(|j| bases[(i >> (j * 2)) & 3] as char).collect();
            let mut lcg = (i as u64).wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1);
            let sequence: String = (0..150)
                .map(|_| {
                    lcg = lcg
                        .wrapping_mul(6_364_136_223_846_793_005)
                        .wrapping_add(1_442_695_040_888_963_407);
                    bases[((lcg >> 33) & 3) as usize] as char
                })
                .collect();
            let name = format!("fam{i}");
            for record in &create_umi_family(&umi, depth, &name, &sequence, 30) {
                writer
                    .write_alignment_record(header, &to_record_buf(record))
                    .expect("write record");
            }
        }
        writer.finish(header).expect("finish");
    }
    std::fs::read(&path).expect("read temp BAM")
}

/// A running pipeline whose writer is stalled, with the handles a test needs to
/// observe it, release it, and inspect what it eventually wrote.
struct StalledRun {
    /// Input bytes the Read step has pulled so far.
    consumed: Arc<AtomicU64>,
    /// Set to release the writer.
    released: Arc<AtomicBool>,
    /// Output bytes accepted after release (record blocks only, no header).
    sink: Arc<Mutex<Vec<u8>>>,
    /// The pipeline itself, yielding the count of items written.
    handle: std::thread::JoinHandle<io::Result<u64>>,
}

/// Spawn a pass-through pipeline over `bam_bytes` whose writer never completes.
fn spawn_stalled_pipeline(
    header: &Header,
    bam_bytes: Vec<u8>,
    num_threads: usize,
    queue_memory_limit: u64,
) -> StalledRun {
    let consumed = Arc::new(AtomicU64::new(0));
    let released = Arc::new(AtomicBool::new(false));
    let sink = Arc::new(Mutex::new(Vec::new()));

    let reader =
        CountingReader { inner: io::Cursor::new(bam_bytes), consumed: Arc::clone(&consumed) };
    let writer = StalledWriter { released: Arc::clone(&released), sink: Arc::clone(&sink) };

    // Production auto-tuning on purpose: the slot counts must stay large
    // enough to swallow the whole test input, so that any bound the test
    // observes comes from the byte budget and not from a queue running out of
    // slots.
    let mut config = PipelineConfig::auto_tuned(num_threads, 1);
    config.queue_memory_limit = queue_memory_limit;
    // A permanently stalled writer is exactly what the deadlock detector is
    // meant to flag, and flagging it would tear the pipeline down before the
    // assertion. Disable it so the test observes backpressure, not recovery.
    config.deadlock_timeout_secs = 0;

    let grouper = Box::new(SingleRecordGrouper::with_header(header.clone()));
    let output_header = header.clone();
    let fns = PipelineFunctions::new(
        |record: RecordBuf| Ok(record),
        move |record: RecordBuf, buf: &mut Vec<u8>| {
            serialize_bam_record_into(&record, &output_header, buf)
        },
    );
    let group_key_config = GroupKeyConfig::new_raw_no_cell(LibraryIndex::from_header(header));

    let handle = std::thread::spawn(move || {
        run_bam_pipeline(
            config,
            Box::new(reader),
            Box::new(writer),
            grouper,
            fns,
            group_key_config,
            None,
        )
    });

    StalledRun { consumed, released, sink, handle }
}

/// Outcome of waiting for the reader to stop pulling input.
struct Consumption {
    /// Input bytes consumed when the wait ended.
    bytes: u64,
    /// Whether consumption actually settled (or reached EOF), as opposed to the
    /// wait timing out with the counter still moving. A timeout means the
    /// caller's premise — that the reader had stopped — never held, so tests
    /// assert on this to fail loudly rather than silently comparing a
    /// still-moving figure.
    settled: bool,
}

/// Wait until input consumption stops growing, or `timeout` elapses.
///
/// Reports the number of input bytes consumed once the counter has held still
/// across `STABLE_SAMPLES` consecutive samples, or as soon as the whole input
/// has been read, with `settled: true`. Several samples rather than one guards
/// against a loaded CI machine descheduling the reader briefly and looking like
/// backpressure. If the deadline is reached with the counter still moving, it
/// reports the last figure with `settled: false`.
fn wait_for_consumption_to_settle(
    consumed: &AtomicU64,
    input_len: u64,
    timeout: Duration,
) -> Consumption {
    /// Consecutive unchanged samples required before calling it settled.
    const STABLE_SAMPLES: u32 = 4;

    let deadline = Instant::now() + timeout;
    let mut previous = u64::MAX;
    let mut stable = 0u32;
    while Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(250));
        let current = consumed.load(Ordering::Relaxed);
        if current >= input_len {
            return Consumption { bytes: current, settled: true };
        }
        if current == previous {
            stable += 1;
            if stable >= STABLE_SAMPLES {
                return Consumption { bytes: current, settled: true };
            }
        } else {
            stable = 0;
        }
        previous = current;
    }
    Consumption { bytes: consumed.load(Ordering::Relaxed), settled: false }
}

/// Join a stalled pipeline within a deadline, returning the count of records it
/// wrote — failing loudly instead of blocking the whole test binary if it hangs.
///
/// A leaked queue byte counter that never returns to zero wedges Read admission:
/// `run_bam_pipeline` never returns and a bare `handle.join()` blocks forever
/// with no diagnostic. Since a wedged admission gate is exactly the defect these
/// tests exist to catch, polling `is_finished()` against a generous deadline
/// turns that hang into a test failure that names how far the input got.
fn join_pipeline_within(
    handle: std::thread::JoinHandle<io::Result<u64>>,
    consumed: &AtomicU64,
    input_len: u64,
    timeout: Duration,
) -> u64 {
    let deadline = Instant::now() + timeout;
    while !handle.is_finished() {
        assert!(
            Instant::now() < deadline,
            "pipeline did not finish within {timeout:?}: consumed {} of {input_len} input bytes \
             — a leaked queue byte counter likely wedged Read admission",
            consumed.load(Ordering::Relaxed),
        );
        std::thread::sleep(Duration::from_millis(50));
    }
    handle.join().expect("pipeline thread should not panic").expect("pipeline should succeed")
}

/// A join deadline generous enough never to fire on a healthy run — the test
/// input is small and drains in well under a second once the writer is released
/// — but bounded so a wedged admission gate fails instead of hanging.
const JOIN_DEADLINE: Duration = Duration::from_secs(60);

/// A stalled writer must stop the Read step, not let it drain the whole input
/// into the pipeline's queues.
///
/// Without a byte-aware admission gate on Read, every downstream queue
/// saturates at its slot count and the reader runs to EOF regardless of
/// `--max-memory` — which is how a slow output device turns into an OOM kill
/// on an input far larger than the host's memory (issue #746).
#[test]
fn stalled_writer_stops_the_reader_within_the_queue_memory_budget() {
    let (header, bam_bytes) = shared_bam_bytes();
    let input_len = bam_bytes.len() as u64;
    // Not merely "exceeds the budget": the reader stops near `budget + overhead`
    // and the assertion below requires a further whole budget left unread, so
    // the fixture needs clear headroom above `read_ahead + TEST_BUDGET_BYTES`.
    // Enforcing a multi-budget floor here keeps that headroom robust to BGZF
    // block-size drift and makes a future `FAMILIES` shrink fail loudly (#789).
    assert!(
        input_len >= MIN_INPUT_HEADROOM_BUDGETS * TEST_BUDGET_BYTES,
        "test input ({input_len} bytes) must be at least {MIN_INPUT_HEADROOM_BUDGETS} budgets \
         ({} bytes) so the read-ahead margin has drift headroom",
        MIN_INPUT_HEADROOM_BUDGETS * TEST_BUDGET_BYTES
    );

    let StalledRun { consumed, released, handle, .. } =
        spawn_stalled_pipeline(header, bam_bytes.clone(), 4, TEST_BUDGET_BYTES);

    let settled = wait_for_consumption_to_settle(&consumed, input_len, Duration::from_secs(30));
    assert!(settled.settled, "reader never stopped under a stalled writer within the timeout");
    // Budget-relative, not a bare fraction of the input: the reader must leave at
    // least one whole queue memory budget's worth of input unread. A naive
    // `< input_len / 2` threshold is marginal for a compressed input only a few
    // budgets in size, and instrumentation (llvm-cov) reschedules the reader
    // enough to nudge consumption past the halfway mark without the gate having
    // failed. Requiring one full budget unread proves the reader stopped
    // meaningfully short while staying robust under that scheduling jitter.
    let unread = input_len - settled.bytes;
    assert!(
        unread >= TEST_BUDGET_BYTES,
        "reader consumed {} of {input_len} input bytes while the writer was stalled, leaving \
         only {unread} unread — less than one {TEST_BUDGET_BYTES}-byte budget; the queue memory \
         budget bounded nothing",
        settled.bytes
    );

    released.store(true, Ordering::Release);
    join_pipeline_within(handle, &consumed, input_len, JOIN_DEADLINE);
}

/// How far the reader runs ahead of a stalled writer must depend on the
/// queue memory budget.
///
/// This is the discriminating check. The previous test could in principle be
/// satisfied by the queues simply running out of *slots*; this one holds the
/// input and the slot counts fixed and varies only `--max-memory`, so a budget
/// that bounds nothing shows up as two identical read-ahead figures.
#[test]
fn read_ahead_under_a_stalled_writer_shrinks_with_the_queue_memory_budget() {
    let (header, bam_bytes) = shared_bam_bytes();
    let input_len = bam_bytes.len() as u64;

    // Both arms must stay gated: the generous budget has to leave the reader
    // stopping short of EOF, or the comparison degenerates into
    // `stalled_writer_stops_the_reader_within_the_queue_memory_budget`'s
    // assertion, which a slot-count-only bound would also satisfy. The reader
    // stops near `budget + overhead`, so the generous budget must clear both that
    // overhead and one further `TEST_BUDGET_BYTES` of gap below `input_len`.
    // Twice the tight budget is the largest multiple this fixture (~4 budgets)
    // admits while keeping the generous arm off EOF.
    let generous_budget = 2 * TEST_BUDGET_BYTES;
    assert!(
        generous_budget + TEST_BUDGET_BYTES < input_len,
        "the generous budget ({generous_budget}) plus one tight budget must stay below the input \
         ({input_len}) so both runs are gated with the reader stopping short of EOF"
    );

    let mut consumption = Vec::new();
    for budget in [TEST_BUDGET_BYTES, generous_budget] {
        let StalledRun { consumed, released, handle, .. } =
            spawn_stalled_pipeline(header, bam_bytes.clone(), 4, budget);
        let settled = wait_for_consumption_to_settle(&consumed, input_len, Duration::from_secs(30));
        assert!(
            settled.settled,
            "reader never stopped under a {budget}-byte budget within the timeout"
        );
        assert!(
            settled.bytes < input_len,
            "the {budget}-byte run consumed all {input_len} input bytes, so this arm reached EOF \
             and was not gated at all"
        );
        released.store(true, Ordering::Release);
        join_pipeline_within(handle, &consumed, input_len, JOIN_DEADLINE);
        consumption.push(settled.bytes);
    }

    // A margin tied to the budget difference, not bare ordering: a scheduler
    // hiccup that made the tight run read one extra block would still pass
    // `tight < generous`, and if the generous run read to EOF a bounded gate would
    // be indistinguishable from none. Requiring the gap to span at least one
    // tight budget pins that the budget — not slot counts or timing — is the
    // bound.
    let (tight, generous) = (consumption[0], consumption[1]);
    assert!(
        generous.saturating_sub(tight) >= TEST_BUDGET_BYTES,
        "read-ahead was {tight} bytes under a {TEST_BUDGET_BYTES}-byte budget and {generous} \
         bytes under a {generous_budget}-byte one; the gap is smaller than one tight budget, so \
         the budget is not bounding the queues"
    );
}

/// A budget smaller than a single read batch must not wedge the pipeline: the
/// `queue_bytes_in_flight() == 0` escape hatch has to admit that first batch.
///
/// This is the case that separates a wrong gate from a mere wrong number. With
/// a healthy writer and a budget of a few bytes, every read batch already
/// exceeds the budget on its own, so admission rests entirely on the empty-in-
/// flight clause of `BamPipelineState::read_admission_allowed`. Without it the
/// reader could never be admitted and the run would hang; with it the pipeline
/// must still emit every record, in order.
#[test]
fn a_budget_smaller_than_one_batch_still_completes_with_every_record() {
    let (header, bam_bytes) = shared_bam_bytes();
    let expected_names = record_names(bam_bytes);

    // Release the writer immediately so it never blocks — a healthy sink — and
    // set a budget far below one decompressed batch.
    let run = spawn_stalled_pipeline(header, bam_bytes.clone(), 4, 8);
    run.released.store(true, Ordering::Release);

    let written =
        join_pipeline_within(run.handle, &run.consumed, bam_bytes.len() as u64, JOIN_DEADLINE);
    assert_eq!(written, expected_names.len() as u64, "every input record must reach the writer");

    // `run_bam_pipeline` writes record blocks only, so re-attach a header before
    // reading the captured stream back as a BAM.
    let mut output = bam_header_bytes(header);
    output.extend_from_slice(&run.sink.lock().expect("sink mutex should not be poisoned"));
    assert_eq!(
        record_names(&output),
        expected_names,
        "output records must match the input exactly, in order"
    );
}

/// The pipeline must still emit every record, in order, once the writer
/// recovers.
///
/// Backpressure that stalls the reader is only safe if releasing the writer
/// lets every record through. The oracle is the input's own record names read
/// back off the output, not a record count: a gate that dropped, duplicated or
/// reordered records while the pipeline was throttled would keep the count
/// intact and change the sequence.
#[test]
fn reader_resumes_and_completes_after_the_writer_recovers() {
    let (header, bam_bytes) = shared_bam_bytes();
    let expected_names = record_names(bam_bytes);
    assert_eq!(expected_names.len(), FAMILIES * DEPTH, "input should hold every generated read");

    let StalledRun { consumed, released, sink, handle } =
        spawn_stalled_pipeline(header, bam_bytes.clone(), 4, TEST_BUDGET_BYTES);

    let settled =
        wait_for_consumption_to_settle(&consumed, bam_bytes.len() as u64, Duration::from_secs(30));
    assert!(settled.settled, "reader never stopped under a stalled writer within the timeout");
    released.store(true, Ordering::Release);

    let written = join_pipeline_within(handle, &consumed, bam_bytes.len() as u64, JOIN_DEADLINE);
    assert_eq!(written, expected_names.len() as u64, "every input record must reach the writer");
    assert_eq!(
        consumed.load(Ordering::Relaxed),
        bam_bytes.len() as u64,
        "the whole input must be consumed once the writer recovers"
    );

    // `run_bam_pipeline` writes record blocks only, so re-attach a header
    // before reading the captured stream back as a BAM.
    let mut output = bam_header_bytes(header);
    output.extend_from_slice(&sink.lock().expect("sink mutex should not be poisoned"));
    assert_eq!(
        record_names(&output),
        expected_names,
        "output records must match the input exactly, in order"
    );
}
