//! Queue-memory backpressure from the output side back to the Read step.
//!
//! The threaded BAM pipeline advertises a queue memory budget (`--max-memory`,
//! logged as "Queue memory budget: N total"). Every stage between Read and
//! Write is bounded, but the bound on most of them is a *slot count*, not a
//! byte count — so when the output device stalls, each stage saturates with
//! however many bytes its slots happen to hold and the budget is not what
//! decides the ceiling.
//!
//! Read is the pipeline's only source of new bytes, and nothing downstream
//! waits on it to make progress, so gating Read on the accounted in-flight
//! bytes bounds the whole pipeline without risking deadlock. These tests pin
//! that behaviour: with a writer that never completes, the pipeline must stop
//! pulling input rather than draining the whole file into its queues.
//!
//! See <https://github.com/fulcrumgenomics/fgumi/issues/746>.

#![allow(clippy::cast_possible_truncation)]

use noodles::bam;
use noodles::sam::Header;
use noodles::sam::alignment::RecordBuf;
use noodles::sam::alignment::io::Write as AlignmentWrite;
use std::io::{self, Read, Write};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};

use crate::helpers::bam_generator::{create_minimal_header, create_umi_family, to_record_buf};
use fgumi_lib::grouper::SingleRecordGrouper;
use fgumi_lib::read_info::LibraryIndex;
use fgumi_lib::unified_pipeline::{
    BatchOrdinal, GroupKeyConfig, PipelineConfig, PipelineFunctions, run_bam_pipeline,
    serialize_bam_record_into,
};

/// Queue memory budget used by the tests, in bytes.
const TEST_BUDGET_BYTES: u64 = 2 * 1024 * 1024;

/// UMI families in the test input, and reads per family.
///
/// Sized so the *compressed* input is several times `TEST_BUDGET_BYTES`. That
/// margin matters in compressed terms specifically: Q1 holds raw BGZF blocks,
/// so if the whole compressed file fits under the budget the reader parks it
/// all in Q1 before any stage downstream builds up and the gate never engages —
/// a smaller input would be swallowed whole and the assertions would prove
/// nothing. The generated bytes are built once and shared (see
/// [`shared_bam_bytes`]) so the tests do not each pay to regenerate them.
///
/// The count is also chosen for *read-ahead* headroom, not just "exceeds the
/// budget". The reader stops once its accounted in-flight bytes reach the
/// budget, and that stopping point — the compressed bytes consumed — is roughly
/// `budget + queue/batch overhead`, essentially independent of the input size.
/// The margin assertions require the reader to leave at least one whole
/// `TEST_BUDGET_BYTES` unread, so the fixture has to clear
/// `read_ahead + TEST_BUDGET_BYTES` by a comfortable margin. At this size the
/// compressed input is roughly `MIN_INPUT_HEADROOM_BUDGETS` budgets, which
/// leaves the reader stopping short by more than one extra budget — headroom
/// that a future toolchain/dependency change to BGZF block sizing (which shifts
/// the read-ahead point) cannot erase without a very large drift. Sizing it
/// this way, rather than by a fraction of the input, is what hardens the tests
/// against that drift (issue #789).
///
/// `DEPTH` is 1 because the reads within a family are identical but for their
/// names, so extra depth barely grows the *compressed* size while it multiplies
/// the records written when the fixture is built. One unique read per family
/// gives the needed compressed margin for the least build cost; the pipeline is
/// exercised with a pass-through grouper, so family structure is immaterial
/// here.
const FAMILIES: usize = 175_000;
const DEPTH: usize = 1;

/// The compressed fixture must be at least this many `TEST_BUDGET_BYTES` in
/// size for the read-ahead margin assertions to carry drift headroom.
///
/// The reader's stopping point sits near `budget + overhead`. The largest
/// budget any test uses is the read-ahead test's generous arm at
/// `3 * TEST_BUDGET_BYTES / 2`, and the margin assertions demand one further
/// budget left unread on top of wherever the reader stops, so anything below
/// three budgets has no slack for BGZF block-size drift (issue #789). The floor
/// holds with room to spare at the current `FAMILIES`: the input measures
/// ~4 budgets and the reader stops by ~1.5, leaving ~2.5 budgets unread on
/// every arm. [`shared_bam_bytes`] asserts this floor once at fixture
/// construction so a future shrink of `FAMILIES` fails loudly for *every* test
/// — not only the one that happens to re-check it — rather than silently
/// reintroducing a thin margin.
const MIN_INPUT_HEADROOM_BUDGETS: u64 = 3;

/// The generated BAM input and the header it was built with, materialized once
/// and shared by every test.
///
/// Building the fixture dominates each test's runtime, and every test wants the
/// same bytes, so this amortizes it across the suite. Tests clone the byte
/// vector when the pipeline needs to own it.
///
/// Enforces the [`MIN_INPUT_HEADROOM_BUDGETS`] floor here, at the single point
/// where the fixture is built, so the guarantee covers every test that reads it
/// — including the read-ahead test, which uses the largest budget and would
/// otherwise have no fixture-size guard at all. A future `FAMILIES` shrink that
/// erodes the read-ahead margin therefore fails loudly and unambiguously.
fn shared_bam_bytes() -> &'static (Header, Vec<u8>) {
    static FIXTURE: OnceLock<(Header, Vec<u8>)> = OnceLock::new();
    FIXTURE.get_or_init(|| {
        let header = create_minimal_header("chr1", 100_000);
        let bytes = build_bam_bytes(&header, FAMILIES, DEPTH);
        let input_len = bytes.len() as u64;
        assert!(
            input_len >= MIN_INPUT_HEADROOM_BUDGETS * TEST_BUDGET_BYTES,
            "test fixture ({input_len} bytes) must be at least {MIN_INPUT_HEADROOM_BUDGETS} \
             budgets ({} bytes) so every read-ahead margin assertion has BGZF block-size drift \
             headroom (issue #789); raise FAMILIES",
            MIN_INPUT_HEADROOM_BUDGETS * TEST_BUDGET_BYTES
        );
        (header, bytes)
    })
}

/// A reader that records how many bytes the pipeline has pulled from the input.
struct CountingReader {
    inner: io::Cursor<Vec<u8>>,
    consumed: Arc<AtomicU64>,
}

impl Read for CountingReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let n = self.inner.read(buf)?;
        self.consumed.fetch_add(n as u64, Ordering::Relaxed);
        Ok(n)
    }
}

/// A writer that blocks every write until it is released, then keeps the bytes.
///
/// Stands in for a saturated output device: the pipeline stays healthy (no
/// error, no panic) but makes no write progress at all. Retaining what it
/// eventually accepts lets the recovery test check record identity rather than
/// just a record count.
struct StalledWriter {
    released: Arc<AtomicBool>,
    sink: Arc<Mutex<Vec<u8>>>,
}

impl Write for StalledWriter {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        // Generous enough never to fire in a passing run; bounded so a failed
        // assertion that unwinds before `released.store(true)` does not leave
        // this thread spinning for the rest of the test binary under
        // `cargo test` (where all tests share one process).
        let deadline = Instant::now() + Duration::from_secs(300);
        while !self.released.load(Ordering::Acquire) {
            if Instant::now() >= deadline {
                return Err(io::Error::new(
                    io::ErrorKind::TimedOut,
                    "StalledWriter was never released",
                ));
            }
            std::thread::sleep(Duration::from_millis(5));
        }
        self.sink.lock().expect("sink mutex should not be poisoned").extend_from_slice(buf);
        Ok(buf.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Serialize `header` as a BAM header stream, the way the pipeline's own entry
/// points do before handing the raw writer to `run_bam_pipeline`.
///
/// `run_bam_pipeline` emits record blocks only, so a captured output stream has
/// to be prefixed with this to be readable as a BAM.
fn bam_header_bytes(header: &Header) -> Vec<u8> {
    let mut writer = bam::io::Writer::new(Vec::new());
    writer.write_header(header).expect("write header");
    let mut bgzf = writer.into_inner();
    bgzf.try_finish().expect("finish header BGZF stream");
    bgzf.into_inner()
}

/// Decode every record out of a BAM byte stream, in order.
///
/// Returns fully decoded [`RecordBuf`]s rather than just names so the identity
/// assertions can compare flags, coordinates, CIGAR, sequence, qualities, and
/// tags — not only that the right names arrived in the right order. Name-only
/// comparison would pass even if the pipeline corrupted any of those fields.
fn record_bufs(bam_bytes: &[u8]) -> Vec<RecordBuf> {
    let mut reader = bam::io::Reader::new(io::Cursor::new(bam_bytes));
    let header = reader.read_header().expect("read header");
    reader.record_bufs(&header).map(|r| r.expect("read record")).collect()
}

/// Build a BAM whose compressed size comfortably exceeds the test budget, so a
/// pipeline that respects the budget cannot swallow all of it.
///
/// Written through a temp file rather than an in-memory buffer so the BGZF
/// stream is finalized exactly the way a real input is.
fn build_bam_bytes(header: &Header, num_families: usize, depth: usize) -> Vec<u8> {
    let bases = [b'A', b'C', b'G', b'T'];
    let dir = tempfile::tempdir().expect("temp dir");
    let path = dir.path().join("input.bam");
    {
        let mut writer =
            bam::io::Writer::new(std::fs::File::create(&path).expect("create temp BAM"));
        writer.write_header(header).expect("write header");
        for i in 0..num_families {
            // Vary both the UMI and the sequence so BGZF cannot collapse the
            // file to a handful of blocks; the queues must hold real bytes.
            let umi: String = (0..8).map(|j| bases[(i >> (j * 2)) & 3] as char).collect();
            let mut lcg = (i as u64).wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1);
            let sequence: String = (0..150)
                .map(|_| {
                    lcg = lcg
                        .wrapping_mul(6_364_136_223_846_793_005)
                        .wrapping_add(1_442_695_040_888_963_407);
                    bases[((lcg >> 33) & 3) as usize] as char
                })
                .collect();
            let name = format!("fam{i}");
            for record in &create_umi_family(&umi, depth, &name, &sequence, 30) {
                writer
                    .write_alignment_record(header, &to_record_buf(record))
                    .expect("write record");
            }
        }
        writer.finish(header).expect("finish");
    }
    std::fs::read(&path).expect("read temp BAM")
}

/// A running pipeline whose writer is stalled, with the handles a test needs to
/// observe it, release it, and inspect what it eventually wrote.
struct StalledRun {
    /// Input bytes the Read step has pulled so far.
    consumed: Arc<AtomicU64>,
    /// Set to release the writer.
    released: Arc<AtomicBool>,
    /// Output bytes accepted after release (record blocks only, no header).
    sink: Arc<Mutex<Vec<u8>>>,
    /// The pipeline itself, yielding the count of items written.
    handle: std::thread::JoinHandle<io::Result<u64>>,
}

/// Spawn a pass-through pipeline over `bam_bytes` whose writer never completes.
///
/// `blocks_per_read_batch` overrides the reader's batch granularity when `Some`;
/// `None` keeps the thread-count-derived production default. Only the read-ahead
/// *scaling* test needs to shrink it — see
/// [`read_ahead_under_a_stalled_writer_shrinks_with_the_queue_memory_budget`] for
/// why the production ~1 MiB batch quantum would otherwise swamp the signal.
fn spawn_stalled_pipeline(
    header: &Header,
    bam_bytes: Vec<u8>,
    num_threads: usize,
    queue_memory_limit: u64,
    blocks_per_read_batch: Option<usize>,
) -> StalledRun {
    let consumed = Arc::new(AtomicU64::new(0));
    let released = Arc::new(AtomicBool::new(false));
    let sink = Arc::new(Mutex::new(Vec::new()));

    let reader =
        CountingReader { inner: io::Cursor::new(bam_bytes), consumed: Arc::clone(&consumed) };
    let writer = StalledWriter { released: Arc::clone(&released), sink: Arc::clone(&sink) };

    // Production auto-tuning on purpose: the slot counts must stay large
    // enough to swallow the whole test input, so that any bound the test
    // observes comes from the byte budget and not from a queue running out of
    // slots.
    let mut config = PipelineConfig::auto_tuned(num_threads, 1);
    // The read granularity, by contrast, is not a slot count and is overridable
    // per test: a finer batch lets the reader stop closer to the byte budget
    // instead of overshooting by up to a whole read batch.
    if let Some(blocks) = blocks_per_read_batch {
        config.blocks_per_read_batch = blocks;
    }
    config.queue_memory_limit = queue_memory_limit;
    // A permanently stalled writer is exactly what the deadlock detector is
    // meant to flag, and flagging it would tear the pipeline down before the
    // assertion. Disable it so the test observes backpressure, not recovery.
    config.deadlock_timeout_secs = 0;

    let grouper = Box::new(SingleRecordGrouper::with_header(header.clone()));
    let output_header = header.clone();
    let fns = PipelineFunctions::new(
        |record: RecordBuf| Ok(record),
        move |record: RecordBuf, buf: &mut Vec<u8>| {
            serialize_bam_record_into(&record, &output_header, buf)
        },
    );
    let group_key_config = GroupKeyConfig::new_raw_no_cell(LibraryIndex::from_header(header));

    let handle = std::thread::spawn(move || {
        run_bam_pipeline(
            config,
            Box::new(reader),
            Box::new(writer),
            grouper,
            fns,
            group_key_config,
            None,
        )
    });

    StalledRun { consumed, released, sink, handle }
}

/// Outcome of waiting for the reader to stop pulling input.
struct Consumption {
    /// Input bytes consumed when the wait ended.
    bytes: u64,
    /// Whether consumption actually settled (or reached EOF), as opposed to the
    /// wait timing out with the counter still moving. A timeout means the
    /// caller's premise — that the reader had stopped — never held, so tests
    /// assert on this to fail loudly rather than silently comparing a
    /// still-moving figure.
    settled: bool,
}

/// Wait until input consumption stops growing, or `timeout` elapses.
///
/// Reports the number of input bytes consumed once the counter has held still
/// across `STABLE_SAMPLES` consecutive samples, or as soon as the whole input
/// has been read, with `settled: true`. Several samples rather than one guards
/// against a loaded CI machine descheduling the reader briefly and looking like
/// backpressure. If the deadline is reached with the counter still moving, it
/// reports the last figure with `settled: false`.
fn wait_for_consumption_to_settle(
    consumed: &AtomicU64,
    input_len: u64,
    timeout: Duration,
) -> Consumption {
    /// Consecutive unchanged samples required before calling it settled.
    const STABLE_SAMPLES: u32 = 4;

    let deadline = Instant::now() + timeout;
    let mut previous = u64::MAX;
    let mut stable = 0u32;
    while Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(250));
        let current = consumed.load(Ordering::Relaxed);
        if current >= input_len {
            return Consumption { bytes: current, settled: true };
        }
        if current == previous {
            stable += 1;
            if stable >= STABLE_SAMPLES {
                return Consumption { bytes: current, settled: true };
            }
        } else {
            stable = 0;
        }
        previous = current;
    }
    Consumption { bytes: consumed.load(Ordering::Relaxed), settled: false }
}

/// Join a stalled pipeline within a deadline, returning the count of records it
/// wrote — failing loudly instead of blocking the whole test binary if it hangs.
///
/// A leaked queue byte counter that never returns to zero wedges Read admission:
/// `run_bam_pipeline` never returns and a bare `handle.join()` blocks forever
/// with no diagnostic. Since a wedged admission gate is exactly the defect these
/// tests exist to catch, polling `is_finished()` against a generous deadline
/// turns that hang into a test failure that names how far the input got.
fn join_pipeline_within(
    handle: std::thread::JoinHandle<io::Result<u64>>,
    consumed: &AtomicU64,
    input_len: u64,
    timeout: Duration,
) -> u64 {
    let deadline = Instant::now() + timeout;
    while !handle.is_finished() {
        assert!(
            Instant::now() < deadline,
            "pipeline did not finish within {timeout:?}: consumed {} of {input_len} input bytes \
             — a leaked queue byte counter likely wedged Read admission",
            consumed.load(Ordering::Relaxed),
        );
        std::thread::sleep(Duration::from_millis(50));
    }
    handle.join().expect("pipeline thread should not panic").expect("pipeline should succeed")
}

/// A join deadline generous enough never to fire on a healthy run — the test
/// input is small and drains in well under a second once the writer is released
/// — but bounded so a wedged admission gate fails instead of hanging.
const JOIN_DEADLINE: Duration = Duration::from_secs(60);

/// A stalled writer must stop the Read step, not let it drain the whole input
/// into the pipeline's queues.
///
/// Without a byte-aware admission gate on Read, every downstream queue
/// saturates at its slot count and the reader runs to EOF regardless of
/// `--max-memory` — which is how a slow output device turns into an OOM kill
/// on an input far larger than the host's memory (issue #746).
#[test]
fn stalled_writer_stops_the_reader_within_the_queue_memory_budget() {
    let (header, bam_bytes) = shared_bam_bytes();
    let input_len = bam_bytes.len() as u64;
    // The fixture's drift headroom — the reader stops near `budget + overhead`
    // and the assertion below requires a further whole budget left unread — is
    // enforced once for every test by the `MIN_INPUT_HEADROOM_BUDGETS` floor in
    // `shared_bam_bytes`, so a `FAMILIES` shrink fails there before reaching here
    // (#789).

    let StalledRun { consumed, released, handle, .. } =
        spawn_stalled_pipeline(header, bam_bytes.clone(), 4, TEST_BUDGET_BYTES, None);

    let settled = wait_for_consumption_to_settle(&consumed, input_len, Duration::from_secs(30));
    assert!(settled.settled, "reader never stopped under a stalled writer within the timeout");
    // Budget-relative, not a bare fraction of the input: the reader must leave at
    // least one whole queue memory budget's worth of input unread. A naive
    // `< input_len / 2` threshold is marginal for a compressed input only a few
    // budgets in size, and instrumentation (llvm-cov) reschedules the reader
    // enough to nudge consumption past the halfway mark without the gate having
    // failed. Requiring one full budget unread proves the reader stopped
    // meaningfully short while staying robust under that scheduling jitter.
    let unread = input_len - settled.bytes;
    assert!(
        unread >= TEST_BUDGET_BYTES,
        "reader consumed {} of {input_len} input bytes while the writer was stalled, leaving \
         only {unread} unread — less than one {TEST_BUDGET_BYTES}-byte budget; the queue memory \
         budget bounded nothing",
        settled.bytes
    );

    released.store(true, Ordering::Release);
    join_pipeline_within(handle, &consumed, input_len, JOIN_DEADLINE);
}

/// How far the reader runs ahead of a stalled writer must depend on the
/// queue memory budget.
///
/// This is the discriminating check. The previous test could in principle be
/// satisfied by the queues simply running out of *slots*; this one holds the
/// input and the slot counts fixed and varies only `--max-memory`, so a budget
/// that bounds nothing shows up as two identical read-ahead figures.
///
/// Two things keep the signal clean and the assertion stable:
///
/// - **A fine read batch.** With the production ~1 MiB read batch the reader
///   overshoots the budget by up to a whole batch, and *which* batch it stops on
///   is scheduling-dependent — so the read-ahead is quantised in ~1 MiB steps
///   and a loaded CI host can land one step off, swamping a budget difference of
///   the same order (that quantisation, not the byte gate, is what made this
///   assertion flap). Shrinking the batch lets the reader stop within a few
///   blocks of the byte budget, so the read-ahead tracks the budget rather than
///   the batch and both arms are deterministic across hosts.
/// - **Sub-saturation budgets.** The compressed read-ahead only rises with the
///   budget while the budget is small: Q3 parks *decoded* (expanded) records, so
///   once the budget is a few MiB the reorder buffer's per-serial cap is what
///   bounds the queue and lifting the budget further barely moves the compressed
///   bytes consumed. Both arms therefore sit in the responsive regime (1 MiB and
///   3 MiB), where doubling-plus the budget produces a clear read-ahead gap.
#[test]
fn read_ahead_under_a_stalled_writer_shrinks_with_the_queue_memory_budget() {
    /// Read batch small enough that read-ahead tracks the byte budget instead of
    /// the ~1 MiB production batch quantum.
    const FINE_READ_BLOCKS: usize = 4;
    /// Reps per arm whose maximum read-ahead is taken as that arm's measurement.
    ///
    /// The budget-bounded stopping point is an *upper* bound the reader
    /// approaches from below, and the only scheduler noise on it is one-sided and
    /// downward: if the reader is starved of CPU for a full second mid-read,
    /// [`wait_for_consumption_to_settle`] can call the arm settled at a partial
    /// read-ahead — well short of where the budget would actually stop it. That
    /// rare downward tail (observed on the generous arm) is what made a single
    /// sample flap (issue #809). It never lifts an arm *above* its true ceiling,
    /// so the maximum across a few reps recovers that ceiling and is immune to
    /// the tail; three reps drive the odds of every rep tailing at once low
    /// enough to be irrelevant while keeping the test cheap.
    const READ_AHEAD_REPS: usize = 3;

    let (header, bam_bytes) = shared_bam_bytes();
    let input_len = bam_bytes.len() as u64;

    // Both budgets stay in the sub-saturation regime (see the doc comment) so the
    // budget actually moves the read-ahead, and both leave the reader well short
    // of EOF on this fixture.
    let tight_budget = TEST_BUDGET_BYTES / 2; // 1 MiB
    let generous_budget = 3 * TEST_BUDGET_BYTES / 2; // 3 MiB
    let budget_difference = generous_budget - tight_budget;

    // Measure one arm's read-ahead: how far the reader runs before a stalled
    // writer backs it up under `budget`. Returned as the settled input-bytes
    // consumed, after asserting the arm actually settled short of EOF.
    let measure_read_ahead = |budget: u64| -> u64 {
        let StalledRun { consumed, released, handle, .. } =
            spawn_stalled_pipeline(header, bam_bytes.clone(), 4, budget, Some(FINE_READ_BLOCKS));
        let settled = wait_for_consumption_to_settle(&consumed, input_len, Duration::from_secs(30));
        assert!(
            settled.settled,
            "reader never stopped under a {budget}-byte budget within the timeout"
        );
        assert!(
            settled.bytes < input_len,
            "the {budget}-byte run consumed all {input_len} input bytes, so this arm reached EOF \
             and was not gated at all"
        );
        released.store(true, Ordering::Release);
        join_pipeline_within(handle, &consumed, input_len, JOIN_DEADLINE);
        settled.bytes
    };

    // Take each arm's *maximum* read-ahead over a few reps, not a single sample:
    // the measurement noise is a one-sided downward tail (see `READ_AHEAD_REPS`),
    // so the max is the robust estimator of the arm's true budget-bounded ceiling.
    let arm_read_ahead = |budget: u64| -> u64 {
        (0..READ_AHEAD_REPS).map(|_| measure_read_ahead(budget)).max().expect("at least one rep")
    };
    let tight = arm_read_ahead(tight_budget);
    let generous = arm_read_ahead(generous_budget);

    // A margin tied to the budget difference, not bare ordering: `tight < generous`
    // alone could be one stray block, and if a bound ignored the budget entirely
    // the two figures would coincide. Requiring the gap to span at least half the
    // budget difference pins that the budget — not slot counts or timing — is the
    // bound, while tolerating the few-block overshoot the fine read batch still
    // leaves. (Measured gap is ~0.9x the budget difference; the reader trails the
    // budget sub-linearly because part of it is spent on decoded, expanded data.)
    assert!(
        generous.saturating_sub(tight) >= budget_difference / 2,
        "read-ahead was {tight} bytes under a {tight_budget}-byte budget and {generous} bytes \
         under a {generous_budget}-byte one; the gap is under half the {budget_difference}-byte \
         budget difference, so the budget is not bounding the queues"
    );
}

/// A budget smaller than a single read batch must not wedge the pipeline: the
/// `queue_bytes_in_flight() == 0` escape hatch has to admit that first batch.
///
/// This is the case that separates a wrong gate from a mere wrong number. With
/// a healthy writer and a budget of a few bytes, every read batch already
/// exceeds the budget on its own, so admission rests entirely on the empty-in-
/// flight clause of `BamPipelineState::read_admission_allowed`. Without it the
/// reader could never be admitted and the run would hang; with it the pipeline
/// must still emit every record, in order.
#[test]
fn a_budget_smaller_than_one_batch_still_completes_with_every_record() {
    let (header, bam_bytes) = shared_bam_bytes();
    let expected_records = record_bufs(bam_bytes);

    // Release the writer immediately so it never blocks — a healthy sink — and
    // set a budget far below one decompressed batch.
    let run = spawn_stalled_pipeline(header, bam_bytes.clone(), 4, 8, None);
    run.released.store(true, Ordering::Release);

    let written =
        join_pipeline_within(run.handle, &run.consumed, bam_bytes.len() as u64, JOIN_DEADLINE);
    assert_eq!(written, expected_records.len() as u64, "every input record must reach the writer");

    // `run_bam_pipeline` writes record blocks only, so re-attach a header before
    // reading the captured stream back as a BAM.
    let mut output = bam_header_bytes(header);
    output.extend_from_slice(&run.sink.lock().expect("sink mutex should not be poisoned"));
    assert_eq!(
        record_bufs(&output),
        expected_records,
        "output records must match the input exactly, in order"
    );
}

/// A budget small enough to bind the processed queue must not wedge the
/// MI-assign stage.
///
/// The processed queue's high-water mark is `min(budget, 256 MiB)` (issue
/// #765), so a small `--max-memory` can pull it below the size of a single
/// processed batch. That matters most with `mi_assign_fn` installed: batches
/// drained out of Q5 stay charged to `processed_heap_bytes` while they sit in
/// `mi_assign_reorder`, so a reorder buffer waiting on a missing serial holds
/// the Process step off at its backpressure check. Forward progress then rests
/// entirely on the Process step pushing an already-held batch unconditionally,
/// ahead of that check.
///
/// Two budgets, because they bind differently. At 4 KiB the Read gate admits
/// one batch at a time, so the mark fires constantly but skew is minimal; at
/// 8 MiB several batches are in flight at once, which is what actually gives
/// the reorder buffer out-of-order serials to park. Both must complete.
///
/// The writer is not stalled here: the hazard is internal to the pipeline, and
/// a stalled writer would mask it behind the Read gate.
#[test]
fn mi_assign_makes_progress_under_a_budget_that_binds_the_processed_queue() {
    let header = create_minimal_header("chr1", 100_000);
    // Enough families to span many batches, few enough to stay quick.
    let bam_bytes = build_bam_bytes(&header, 20_000, DEPTH);
    let expected_records = record_bufs(&bam_bytes);

    for budget in [4096u64, 8 * 1024 * 1024] {
        let sink = Arc::new(Mutex::new(Vec::new()));
        let writer =
            StalledWriter { released: Arc::new(AtomicBool::new(true)), sink: Arc::clone(&sink) };

        let mut config = PipelineConfig::auto_tuned(4, 1);
        config.queue_memory_limit = budget;
        // Unlike the stalled-writer tests above, the deadlock detector stays
        // ON here (default: 10s, detection only). This test asserts liveness,
        // so a wedge should surface as a failed run rather than as a hang that
        // only the harness timeout catches.
        assert!(!config.deadlock_recover_enabled, "detection only, so a wedge is not papered over");

        let grouper = Box::new(SingleRecordGrouper::with_header(header.clone()));
        let output_header = header.clone();
        // Record each hook invocation's ordinal in call order. The contract is
        // that `mi_assign_fn` runs in strict `(batch_serial, idx_in_batch)`
        // order (see `BatchOrdinal`); the write reorder buffer can restore
        // output order even if the hook fired out of order, so a name-order
        // check on the output alone cannot see a violation of that contract.
        let hook_ordinals = Arc::new(Mutex::new(Vec::<(u64, usize)>::new()));
        let hook_ordinals_inner = Arc::clone(&hook_ordinals);
        let fns = PipelineFunctions::new(
            |record: RecordBuf| Ok(record),
            move |record: RecordBuf, buf: &mut Vec<u8>| {
                serialize_bam_record_into(&record, &output_header, buf)
            },
        )
        .with_mi_assign(move |ordinal: BatchOrdinal, _item: &mut RecordBuf| {
            hook_ordinals_inner
                .lock()
                .expect("hook ordinals mutex should not be poisoned")
                .push((ordinal.batch_serial, ordinal.idx_in_batch));
            Ok(())
        });
        let group_key_config = GroupKeyConfig::new_raw_no_cell(LibraryIndex::from_header(&header));

        let written = run_bam_pipeline(
            config,
            Box::new(io::Cursor::new(bam_bytes.clone())),
            Box::new(writer),
            grouper,
            fns,
            group_key_config,
            None,
        )
        .unwrap_or_else(|e| panic!("budget {budget}: pipeline must complete, got {e}"));

        assert_eq!(
            written,
            expected_records.len() as u64,
            "budget {budget}: every input record must reach the writer"
        );

        let ordinals = hook_ordinals.lock().expect("hook ordinals mutex should not be poisoned");
        assert_eq!(
            ordinals.len(),
            expected_records.len(),
            "budget {budget}: the MI-assign hook must run once per item"
        );
        // The hook must be invoked in strictly increasing `(batch_serial,
        // idx_in_batch)` order — the serial-order contract it exists to
        // provide. `Vec::is_sorted` alone would accept duplicates, so pair it
        // with a strict-monotonicity check via `windows`.
        assert!(
            ordinals.windows(2).all(|w| w[0] < w[1]),
            "budget {budget}: MI-assign hook fired out of serial order: {ordinals:?}"
        );

        let mut output = bam_header_bytes(&header);
        output.extend_from_slice(&sink.lock().expect("sink mutex should not be poisoned"));
        assert_eq!(
            record_bufs(&output),
            expected_records,
            "budget {budget}: output must match the input exactly, in order"
        );
    }
}

/// The pipeline must still emit every record, in order, once the writer
/// recovers.
///
/// Backpressure that stalls the reader is only safe if releasing the writer
/// lets every record through. The oracle is the input's own record names read
/// back off the output, not a record count: a gate that dropped, duplicated or
/// reordered records while the pipeline was throttled would keep the count
/// intact and change the sequence.
#[test]
fn reader_resumes_and_completes_after_the_writer_recovers() {
    let (header, bam_bytes) = shared_bam_bytes();
    let expected_records = record_bufs(bam_bytes);
    assert_eq!(expected_records.len(), FAMILIES * DEPTH, "input should hold every generated read");

    let StalledRun { consumed, released, sink, handle } =
        spawn_stalled_pipeline(header, bam_bytes.clone(), 4, TEST_BUDGET_BYTES, None);

    let settled =
        wait_for_consumption_to_settle(&consumed, bam_bytes.len() as u64, Duration::from_secs(30));
    assert!(settled.settled, "reader never stopped under a stalled writer within the timeout");
    released.store(true, Ordering::Release);

    let written = join_pipeline_within(handle, &consumed, bam_bytes.len() as u64, JOIN_DEADLINE);
    assert_eq!(written, expected_records.len() as u64, "every input record must reach the writer");
    assert_eq!(
        consumed.load(Ordering::Relaxed),
        bam_bytes.len() as u64,
        "the whole input must be consumed once the writer recovers"
    );

    // `run_bam_pipeline` writes record blocks only, so re-attach a header
    // before reading the captured stream back as a BAM.
    let mut output = bam_header_bytes(header);
    output.extend_from_slice(&sink.lock().expect("sink mutex should not be poisoned"));
    assert_eq!(
        record_bufs(&output),
        expected_records,
        "output records must match the input exactly, in order"
    );
}
