//! `Duplex` command implementation.
//!
//! This command takes grouped reads (with MI tags ending in /A and /B) and generates
//! duplex consensus reads by performing two-stage consensus calling:
//! 1. Single-strand consensus for /A and /B reads separately
//! 2. Duplex consensus from paired single-strand consensuses
//!
//! When `--rejects` is set, the declarative chain (see [`crate::pipeline::chains`])
//! routes rejected records through its rejects fan-out branch, landing in
//! batch-input order. The rejects BAM advertises the input header so
//! raw-input RG/PG/contig metadata is preserved. The pattern matches
//! `commands::filter`, `commands::correct`, and `commands::simplex`.

use anyhow::{Result, bail};
use clap::Parser;
use std::path::Path;

use super::command::Command;
use super::common::{
    AllowUnmappedOptions, BamIoOptions, CompressionOptions, ConsensusCallingOptions,
    OverlappingConsensusOptions, QueueMemoryOptions, ReadGroupOptions, RejectsOptions,
    SchedulerOptions, StatsOptions, ThreadingOptions, reject_output_collisions,
};
use crate::duplex_consensus_caller::DuplexConsensusCaller;
use crate::sam::SamTag;
use fgumi_raw_bam;
use fgumi_raw_bam::RawRecord;

/// Call duplex consensus reads from grouped reads with /A and /B MI tags
#[derive(Parser, Debug)]
#[command(
    name = "duplex",
    about = "\x1b[38;5;180m[CONSENSUS]\x1b[0m      \x1b[36mCall duplex consensus sequences from UMI-grouped reads\x1b[0m",
    long_about = r#"
Calls duplex consensus sequences from reads generated from the same double-stranded source molecule. Prior
to running this tool, reads must have been grouped with `group` using the `paired` strategy. Doing
so will apply (by default) MI tags to all reads of the form `*/A` and `*/B` where the /A and /B suffixes
with the same identifier denote reads that are derived from opposite strands of the same source duplex molecule.

Reads from the same unique molecule are first partitioned by source strand and assembled into single
strand consensus molecules as described by the simplex command. Subsequently, for molecules that
have at least one observation of each strand, duplex consensus reads are assembled by combining the evidence
from the two single strand consensus reads.

Because of the nature of duplex sequencing, this tool does not support fragment reads - if found in the
input they are ignored. Similarly, read pairs for which consensus reads cannot be generated for one or
other read (R1 or R2) are omitted from the output.

The consensus reads produced are unaligned, due to the difficulty and error-prone nature of inferring the consensus
alignment. Consensus reads should therefore be aligned after, which should not be too expensive as likely there
are far fewer consensus reads than input raw reads.

Consensus reads have a number of additional optional tags set in the resulting BAM file. The tag names follow
a pattern where the first letter (a, b or c) denotes that the tag applies to the first single strand consensus (a),
second single-strand consensus (b) or the final duplex consensus (c). The second letter is intended to capture
the meaning of the tag (e.g. d=depth, m=min depth, e=errors/error-rate) and is upper case for values that are
one per read and lower case for values that are one per base.

The tags break down into those that are single-valued per read:

  consensus depth      [aD,bD,cD] (int)  : the maximum depth of raw reads at any point in the consensus reads
  consensus min depth  [aM,bM,cM] (int)  : the minimum depth of raw reads at any point in the consensus reads
  consensus error rate [aE,bE,cE] (float): the fraction of bases in raw reads disagreeing with the final consensus calls

And those that have a value per base (duplex values are not generated, but can be generated by summing):

  consensus depth  [ad,bd] (short[]): the count of bases contributing to each single-strand consensus read at each position
  consensus errors [ae,be] (short[]): the count of bases from raw reads disagreeing with the final single-strand consensus base
  consensus bases  [ac,bc] (string) : the single-strand consensus bases
  consensus quals  [aq,bq] (string) : the single-strand consensus qualities

The per base depths and errors are both capped at 32,767. In all cases no-calls (Ns) and bases below the
min-input-base-quality are not counted in tag value calculations.

The --min-reads option can take 1-3 values similar to `filter`. Values are comma-delimited in
fgumi (whereas fgbio's `CallDuplexConsensusReads` takes them space-separated). For example:

  fgumi duplex ... --min-reads 10,5,3

If fewer than three values are supplied, the last value is repeated (i.e. `5,4` -> `5 4 4` and `1` -> `1 1 1`). The
first value applies to the final consensus read, the second value to one single-strand consensus, and the last
value to the other single-strand consensus. It is required that if values two and three differ,
the more stringent value comes earlier.
"#
)]
pub struct Duplex {
    /// Input and output BAM files
    #[command(flatten)]
    pub io: BamIoOptions,

    /// Optional output BAM file for rejected reads
    #[command(flatten)]
    pub rejects_opts: RejectsOptions,

    /// Optional output file for consensus calling statistics
    #[command(flatten)]
    pub stats_opts: StatsOptions,

    /// Read group options
    #[command(flatten)]
    pub read_group: ReadGroupOptions,

    /// Consensus calling options
    #[command(flatten)]
    pub consensus: ConsensusCallingOptions,

    /// Overlapping consensus options
    #[command(flatten)]
    pub overlapping: OverlappingConsensusOptions,

    /// Threading options for parallel processing
    #[command(flatten)]
    pub threading: ThreadingOptions,

    /// Compression options for output BAM.
    #[command(flatten)]
    pub compression: CompressionOptions,

    /// Minimum reads for consensus calling.
    ///
    /// Can specify 1-3 values: \[duplex\] or \[duplex, AB/BA\] or \[duplex, AB, BA\]. The values
    /// must be given high to low — no value may exceed the one before it — so `7,3,1` is
    /// accepted and `1,2` is rejected. Values may be 0: `1,1,0` emits a consensus for a
    /// molecule observed on only one strand, so every molecule is collapsed whether or not it
    /// makes duplex.
    #[arg(short = 'M', long = "min-reads", value_delimiter = ',', default_value = "1")]
    pub min_reads: Vec<usize>,

    /// Maximum number of reads to use when building a single-strand consensus.
    ///
    /// If more than this many reads are present for a strand, that strand is downsampled to
    /// exactly this many reads. The cap is applied independently to each end of each strand.
    ///
    /// Which reads are retained is determined by a hash of the read names, so the selection is
    /// reproducible across runs, thread counts, and execution modes. Mates share a read name and
    /// therefore a rank, so both ends of a template are normally retained or discarded together;
    /// because each end is capped independently, a template whose R1 survives upstream alignment
    /// filtering while its R2 does not can shift the cap boundary on one end alone, and then the
    /// two ends' retained subsets diverge. This matches fgbio's structure.
    #[arg(long = "max-reads-per-strand")]
    pub max_reads_per_strand: Option<usize>,

    /// Whether to process unmapped reads (the shared `--allow-unmapped` flag).
    #[command(flatten)]
    pub allow_unmapped: AllowUnmappedOptions,

    /// Scheduler and pipeline stats options
    #[command(flatten)]
    pub scheduler_opts: SchedulerOptions,

    /// Queue memory options.
    #[command(flatten)]
    pub queue_memory: QueueMemoryOptions,

    /// Methylation-aware consensus calling mode.
    /// EM-Seq: C→T at ref-C = unmethylated (enzymatic conversion); TAPs: C→T at ref-C = methylated.
    /// Emits MM/ML methylation tags and cu/ct per-base count tags on consensus reads.
    /// Requires --ref.
    #[arg(long = "methylation-mode", value_enum)]
    pub methylation_mode: Option<crate::commands::common::MethylationModeArg>,

    /// Path to the reference FASTA file (required when --methylation-mode is set).
    #[arg(long = "ref")]
    pub reference: Option<std::path::PathBuf>,
}

// ─────────────────────────────────────────────────────────────────────────────
// DuplexOptions — the stage's tuning knobs, projected out of the CLI struct
// ─────────────────────────────────────────────────────────────────────────────

/// Duplex-stage tuning, independent of how the values were supplied.
///
/// See [`crate::commands::zipper::ZipperOptions`] for why this is a plain
/// struct rather than a flattened `clap::Args`. Note that the consensus-calling
/// knobs are held **flat** here even though [`Duplex`] nests them behind
/// `#[command(flatten)]` sub-structs: the chain builder wants one bag per stage,
/// not a re-run of the CLI's grouping.
#[derive(Debug, Clone)]
pub struct DuplexOptions {
    /// Pre-UMI error rate (phred).
    pub error_rate_pre_umi: u8,
    /// Post-UMI error rate (phred).
    pub error_rate_post_umi: u8,
    /// Minimum input base quality.
    pub min_input_base_quality: u8,
    /// Emit per-base consensus tags.
    pub output_per_base_tags: bool,
    /// Trim consensus reads.
    pub trim: bool,
    /// Minimum consensus base quality.
    pub min_consensus_base_quality: u8,
    /// How to resolve a near-tie between the two most likely consensus bases.
    pub tie_rule: fgumi_consensus::TieRule,
    /// Call overlapping bases jointly.
    pub consensus_call_overlapping_bases: bool,
    /// Minimum reads per consensus, per tier.
    pub min_reads: Vec<usize>,
    /// Cap on reads per strand.
    pub max_reads_per_strand: Option<usize>,
    /// Let fully-unmapped primary templates through the pre-group filter.
    ///
    /// Carried as the whole flattened sub-struct, like `io` / `rejects_opts` /
    /// `read_group`, rather than as a bare `bool`.
    pub allow_unmapped: AllowUnmappedOptions,
    /// Input/output paths and reader mode.
    pub io: BamIoOptions,
    /// Optional rejects output.
    pub rejects_opts: RejectsOptions,
    /// Optional stats output.
    pub stats_opts: StatsOptions,
    /// Read-group identity for emitted reads.
    pub read_group: ReadGroupOptions,
    /// Resolved methylation calling mode (`Disabled` when the flag is unset).
    pub methylation_mode: fgumi_consensus::MethylationMode,
    /// Reference FASTA for methylation-aware modes.
    pub reference: Option<std::path::PathBuf>,
}

impl Default for DuplexOptions {
    /// Test/`runall`-construction default: consensus/overlapping knobs from the
    /// shared option defaults, `min_reads = [1]`, methylation disabled.
    fn default() -> Self {
        let consensus = ConsensusCallingOptions::default();
        let overlapping = OverlappingConsensusOptions::default();
        Self {
            error_rate_pre_umi: consensus.error_rate_pre_umi,
            error_rate_post_umi: consensus.error_rate_post_umi,
            min_input_base_quality: consensus.min_input_base_quality,
            output_per_base_tags: consensus.output_per_base_tags,
            trim: consensus.trim,
            min_consensus_base_quality: consensus.min_consensus_base_quality,
            tie_rule: consensus.tie_rule.into(),
            consensus_call_overlapping_bases: overlapping.consensus_call_overlapping_bases,
            min_reads: vec![1],
            max_reads_per_strand: None,
            allow_unmapped: AllowUnmappedOptions { enabled: false },
            io: BamIoOptions::default(),
            rejects_opts: RejectsOptions::default(),
            stats_opts: StatsOptions::default(),
            read_group: ReadGroupOptions::default(),
            methylation_mode: fgumi_consensus::MethylationMode::default(),
            reference: None,
        }
    }
}

impl Duplex {
    /// Project the parsed CLI flags into [`DuplexOptions`].
    #[must_use]
    pub fn to_duplex_options(&self) -> DuplexOptions {
        DuplexOptions {
            error_rate_pre_umi: self.consensus.error_rate_pre_umi,
            error_rate_post_umi: self.consensus.error_rate_post_umi,
            min_input_base_quality: self.consensus.min_input_base_quality,
            output_per_base_tags: self.consensus.output_per_base_tags,
            trim: self.consensus.trim,
            min_consensus_base_quality: self.consensus.min_consensus_base_quality,
            tie_rule: self.consensus.tie_rule.into(),
            consensus_call_overlapping_bases: self.overlapping.consensus_call_overlapping_bases,
            min_reads: self.min_reads.clone(),
            max_reads_per_strand: self.max_reads_per_strand,
            allow_unmapped: self.allow_unmapped.clone(),
            io: self.io.clone(),
            rejects_opts: self.rejects_opts.clone(),
            stats_opts: self.stats_opts.clone(),
            read_group: self.read_group.clone(),
            methylation_mode: crate::commands::common::resolve_methylation_mode(
                self.methylation_mode,
            ),
            reference: self.reference.clone(),
        }
    }
}

impl DuplexOptions {
    /// Reconstruct the shared [`ConsensusCallingOptions`] from the inlined flat
    /// fields, so the chain builder can read `.consensus().error_rate_pre_umi`
    /// etc. `tie_rule` is stored resolved on `DuplexOptions`; convert it back to
    /// the CLI-facing [`crate::commands::common::TieRuleArg`] via the 1:1 mapping.
    #[must_use]
    pub fn consensus(&self) -> ConsensusCallingOptions {
        ConsensusCallingOptions {
            error_rate_pre_umi: self.error_rate_pre_umi,
            error_rate_post_umi: self.error_rate_post_umi,
            min_input_base_quality: self.min_input_base_quality,
            output_per_base_tags: self.output_per_base_tags,
            trim: self.trim,
            min_consensus_base_quality: self.min_consensus_base_quality,
            tie_rule: self.tie_rule.into(),
        }
    }

    /// Reconstruct the shared [`OverlappingConsensusOptions`] from the inlined
    /// flat field.
    #[must_use]
    pub fn overlapping(&self) -> OverlappingConsensusOptions {
        OverlappingConsensusOptions {
            consensus_call_overlapping_bases: self.consensus_call_overlapping_bases,
        }
    }
}

impl Command for Duplex {
    /// Executes the duplex consensus calling pipeline.
    ///
    /// This method processes grouped reads with MI tags ending in /A and /B suffixes to generate
    /// duplex consensus reads. The process involves:
    /// 1. Creating a duplex consensus caller with specified parameters
    /// 2. Opening input BAM and creating output BAM writer
    /// 3. Processing templates through the template iterator
    /// 4. Calling consensus for each template
    /// 5. Writing consensus reads to output
    /// 6. Optionally writing rejected reads to a separate BAM
    /// 7. Logging statistics
    ///
    /// The cell barcode tag is fixed to the SAM standard `CB` tag.
    ///
    /// # Returns
    ///
    /// `Ok(())` on success.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - Input BAM cannot be opened or read
    /// - Output BAM cannot be created or written
    /// - Template processing encounters errors
    /// - Consensus calling fails
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use fgumi_lib::commands::duplex::Duplex;
    /// # use fgumi_lib::commands::command::Command;
    /// # use fgumi_lib::commands::common::{
    /// #     AllowUnmappedOptions, BamIoOptions, CompressionOptions, ConsensusCallingOptions,
    /// #     OverlappingConsensusOptions, QueueMemoryOptions, ReadGroupOptions, RejectsOptions,
    /// #     SchedulerOptions, StatsOptions, ThreadingOptions,
    /// # };
    /// # use std::path::{Path, PathBuf};
    /// let duplex = Duplex {
    ///     io: BamIoOptions {
    ///         input: PathBuf::from("grouped.bam"),
    ///         output: PathBuf::from("duplex.bam"),
    ///         async_reader: false,
    ///         check_crc: false,
    ///         no_check_crc: false,
    ///     },
    ///     rejects_opts: RejectsOptions::default(),
    ///     stats_opts: StatsOptions::default(),
    ///     read_group: ReadGroupOptions {
    ///         read_name_prefix: Some("consensus".to_string()),
    ///         read_group_id: "duplex".to_string(),
    ///     },
    ///     consensus: ConsensusCallingOptions {
    ///         output_per_base_tags: false,
    ///         ..ConsensusCallingOptions::default()
    ///     },
    ///     overlapping: OverlappingConsensusOptions::default(),
    ///     threading: ThreadingOptions::none(),
    ///     compression: CompressionOptions::default(),
    ///     min_reads: vec![1],
    ///     max_reads_per_strand: None,
    ///     allow_unmapped: AllowUnmappedOptions { enabled: false },
    ///     scheduler_opts: SchedulerOptions::default(),
    ///     queue_memory: QueueMemoryOptions::default(),
    ///     methylation_mode: None,
    ///     reference: None,
    /// };
    ///
    /// duplex.execute("test")?;
    /// # Ok::<(), anyhow::Error>(())
    /// ```
    fn execute(&self, command_line: &str) -> Result<()> {
        // Validate the input exists (stdin paths are exempt — the reader
        // streams them in a single pass).
        self.io.validate()?;
        let mut outputs: Vec<(&Path, &str)> = vec![(self.io.output.as_path(), "--output")];
        if let Some(path) = &self.rejects_opts.rejects {
            outputs.push((path.as_path(), "--rejects"));
        }
        if let Some(path) = &self.stats_opts.stats {
            outputs.push((path.as_path(), "--stats"));
        }
        reject_output_collisions(&outputs)?;

        // Validate consensus arguments (e.g. error rates must be > 0).
        self.validate()?;

        if self.reference.is_some() && self.methylation_mode.is_none() {
            bail!("--ref requires --methylation-mode to be set");
        }

        // The declarative chain is the only execution path: `execute` runs the
        // reader-free pre-flight above (io.validate / output-collision /
        // validate / the `--ref requires --methylation-mode` bail) and then
        // always dispatches to `execute_chain`, with or without `--threads`
        // (absent `--threads` runs the chain at a single worker). `add_duplex`
        // logs the `Calling duplex consensus` timer and the `Starting Duplex`
        // banner + option lines; the duplex finalize hook logs the overlapping
        // stats, the summary, and the `--stats` TSV. Running any of those here
        // would double-log and pre-consume stdin, so `execute` only does the
        // pre-flight above.
        self.execute_chain(command_line)
    }
}

impl Duplex {
    /// Validates command-line arguments prior to execution.
    ///
    /// Mirrors fgbio's `CallDuplexConsensusReads` argument validation: both the
    /// pre- and post-UMI Phred-scaled error rates must be strictly greater than
    /// zero. A rate of Q0 corresponds to `P(error) = 1`, which is nonsensical as
    /// a prior and would corrupt the duplex consensus quality model, so fgbio
    /// rejects it (`CallDuplexConsensusReads.scala:131-132`).
    fn validate(&self) -> Result<()> {
        if self.consensus.error_rate_pre_umi == 0 {
            bail!("error-rate-pre-umi must be > 0");
        }
        if self.consensus.error_rate_post_umi == 0 {
            bail!("error-rate-post-umi must be > 0");
        }
        // `--min-reads` is deliberately not bounded below, matching fgbio, which validates
        // only the ordering -- each value no larger than the one before it
        // (`total >= XY >= YX`). A 0 in the per-strand slots is fgbio's single-strand mode
        // (`-M 1 1 0`), where a molecule observed on only one strand still yields a
        // consensus. A total of 0 is equivalent to 1 rather than degenerate, because the
        // check it feeds (`min_total <= num_xy + num_yx`) is only reached for a group that
        // already has at least one read. This is why `duplex` differs from `simplex` and
        // `codec`, where a 0 really would make the filter a silent no-op.
        //
        // The ordering rule itself is `DuplexConsensusCaller`'s, applied here so that both
        // execution paths reject a bad value before any I/O. `--threads` mode builds its
        // caller inside the pipeline's per-batch closure, i.e. after the output BAM has
        // been created, so relying on the constructor alone would turn an argument error
        // into a mid-run worker failure that leaves a partial output file behind.
        DuplexConsensusCaller::validate_min_reads(&self.min_reads)?;

        // `--max-reads-per-strand 0` empties every strand, so no molecule can produce a
        // consensus. fgbio failed deep in consensus calling with a bare
        // `IllegalArgumentException` (fixed in fulcrumgenomics/fgbio#1166); fgumi was quieter
        // still, exiting 0 having written an empty BAM. Only a lower bound is checked here,
        // matching fgbio: unlike `simplex` and `codec`, duplex cannot compare the cap against
        // `--min-reads` (a vector with its own ordering rule), and a cap below it is already
        // handled gracefully -- `consensus_call` returns no consensus rather than panicking.
        if self.max_reads_per_strand == Some(0) {
            bail!("--max-reads-per-strand must be >= 1");
        }
        Ok(())
    }

    /// Run the duplex stage on the declarative chain builder — the only
    /// execution path, with or without `--threads`.
    ///
    /// The chain opens its own source, validates the template-coordinate sort
    /// order, calls consensus, writes the output BAM, and writes the
    /// rejects/stats via `DuplexFinalizeHook`. `--threads 1` (or absent
    /// `--threads`) runs the chain at a single worker, which is the in-process
    /// parity oracle for the multi-worker case (see
    /// `test_duplex_chain_matches_single_threaded`).
    fn execute_chain(&self, command_line: &str) -> Result<()> {
        use crate::pipeline::chains::{
            ChainSpec, SingleStageContext, Stage, StageOptionsBag, build_for,
        };
        self.io.log_effective_check_crc();
        let stage_opts =
            StageOptionsBag { duplex: Some(self.to_duplex_options()), ..Default::default() };
        let ctx = SingleStageContext {
            io: &self.io,
            threading: &self.threading,
            compression: &self.compression,
            scheduler: &self.scheduler_opts,
            queue_memory: &self.queue_memory,
            command_line,
        };
        let spec = ChainSpec::single_stage(Stage::Duplex, stage_opts, &ctx);
        build_for(spec)?.run()
    }
}

/// Check if a group of raw-byte BAM records has both /A and /B strands.
///
/// This is the raw-byte equivalent of `DuplexConsensusCaller::has_both_strands`.
/// It examines the MI tag of each record to check for /A and /B suffixes.
/// Returns `true` only if there is at least one read with /A suffix AND at least
/// one read with /B suffix.
pub(crate) fn has_both_strands_raw(records: &[RawRecord]) -> bool {
    if records.len() < 2 {
        return false;
    }

    let mut has_a = false;
    let mut has_b = false;

    for raw in records {
        if let Some(mi_bytes) = fgumi_raw_bam::find_string_tag_in_record(raw, SamTag::MI) {
            // Strip trailing NUL if present (raw BAM Z-tags may be NUL-terminated)
            let mi_bytes = mi_bytes.strip_suffix(&[0]).unwrap_or(mi_bytes);
            if mi_bytes.len() >= 2 {
                let len = mi_bytes.len();
                if mi_bytes[len - 2] == b'/' {
                    match mi_bytes[len - 1] {
                        b'A' => {
                            has_a = true;
                            if has_b {
                                return true;
                            }
                        }
                        b'B' => {
                            has_b = true;
                            if has_a {
                                return true;
                            }
                        }
                        _ => {}
                    }
                }
            }
        }
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every tuning flag must survive the projection into [`DuplexOptions`].
    /// See the simplex counterpart for why this parses rather than constructs.
    #[test]
    fn to_duplex_options_carries_every_tuning_flag() {
        let cmd = Duplex::try_parse_from([
            "duplex",
            "-i",
            "in.bam",
            "-o",
            "out.bam",
            "--error-rate-pre-umi",
            "41",
            "--error-rate-post-umi",
            "36",
            "--min-input-base-quality",
            "18",
            "--output-per-base-tags=false",
            "--trim=true",
            "--min-consensus-base-quality",
            "21",
            "--tie-rule",
            "ulp-relative",
            "--consensus-call-overlapping-bases=false",
            "--min-reads",
            "3,2,1",
            "--max-reads-per-strand",
            "55",
            "--rejects",
            "rej.bam",
            "--stats",
            "stats.txt",
            "--read-group-id",
            "Z",
            "--read-name-prefix",
            "pfx",
            "--methylation-mode",
            "em-seq",
            "--ref",
            "ref.fa",
            "--allow-unmapped=true",
        ])
        .expect("parses");

        let opts = cmd.to_duplex_options();

        assert_eq!(opts.error_rate_pre_umi, 41);
        assert_eq!(opts.error_rate_post_umi, 36);
        assert_eq!(opts.min_input_base_quality, 18);
        assert!(!opts.output_per_base_tags, "an explicit false must not be lost");
        assert!(opts.trim);
        assert_eq!(opts.min_consensus_base_quality, 21);
        assert_eq!(
            opts.tie_rule,
            fgumi_consensus::TieRule::UlpRelative,
            "--tie-rule must reach the projection"
        );
        assert!(!opts.consensus_call_overlapping_bases);
        assert_eq!(opts.min_reads, vec![3, 2, 1]);
        assert_eq!(opts.max_reads_per_strand, Some(55));
        assert!(opts.allow_unmapped.enabled, "--allow-unmapped must reach the projection");
        assert_eq!(
            opts.methylation_mode,
            fgumi_consensus::MethylationMode::EmSeq,
            "--methylation-mode must reach the projection",
        );
        assert_eq!(opts.reference, Some(std::path::PathBuf::from("ref.fa")));
        // The flattened sub-structs must come across whole, not field by field.
        assert_eq!(opts.io.input, std::path::PathBuf::from("in.bam"));
        assert_eq!(opts.io.output, std::path::PathBuf::from("out.bam"));
        assert_eq!(opts.rejects_opts.rejects, Some(std::path::PathBuf::from("rej.bam")));
        assert_eq!(opts.stats_opts.stats, Some(std::path::PathBuf::from("stats.txt")));
        assert_eq!(opts.read_group.read_group_id, "Z");
        assert_eq!(opts.read_group.read_name_prefix, Some("pfx".to_string()));
    }

    /// The projection must carry defaults faithfully too — a field hard-coded to
    /// the value the non-default test happens to pass would slip through it.
    #[test]
    fn to_duplex_options_carries_defaults() {
        let cmd =
            Duplex::try_parse_from(["duplex", "-i", "in.bam", "-o", "out.bam"]).expect("parses");

        let opts = cmd.to_duplex_options();

        assert_eq!(opts.error_rate_pre_umi, 45);
        assert_eq!(opts.error_rate_post_umi, 40);
        assert_eq!(opts.min_input_base_quality, 10);
        assert!(opts.output_per_base_tags);
        assert!(!opts.trim);
        assert_eq!(opts.min_consensus_base_quality, 2);
        assert_eq!(opts.tie_rule, fgumi_consensus::TieRule::FgbioCompat);
        assert!(opts.consensus_call_overlapping_bases);
        assert_eq!(opts.min_reads, vec![1]);
        assert_eq!(opts.max_reads_per_strand, None);
        assert!(!opts.allow_unmapped.enabled);
        assert_eq!(opts.methylation_mode, fgumi_consensus::MethylationMode::Disabled);
        assert_eq!(opts.reference, None);
        assert_eq!(opts.rejects_opts.rejects, None);
        assert_eq!(opts.stats_opts.stats, None);
        assert_eq!(opts.read_group.read_group_id, "A");
        assert_eq!(opts.read_group.read_name_prefix, None);
    }

    use anyhow::Result;
    use fgumi_bam_io::{create_bam_reader, create_bam_writer};
    use fgumi_raw_bam::{
        SamBuilder as RawSamBuilder, flags, raw_record_to_record_buf, testutil::encode_op,
    };
    use noodles::sam;
    use noodles::sam::alignment::io::Write as AlignmentWrite;
    use noodles::sam::alignment::record::data::field::Tag;
    use noodles::sam::alignment::record_buf::data::field::Value;
    use noodles::sam::header::record::value::Map;
    use noodles::sam::header::record::value::map::ReferenceSequence;
    use rstest::rstest;
    use std::collections::HashSet;
    use std::num::NonZeroUsize;
    use std::path::PathBuf;
    use tempfile::{NamedTempFile, TempDir};

    /// Helper struct for managing temporary test file paths.
    struct TestPaths {
        #[allow(dead_code)]
        dir: TempDir,
        pub output: PathBuf,
    }

    impl TestPaths {
        fn new() -> Result<Self> {
            let dir = TempDir::new()?;
            Ok(Self { output: dir.path().join("output.bam"), dir })
        }

        fn output_n(&self, n: usize) -> PathBuf {
            self.dir.path().join(format!("output{n}.bam"))
        }
    }

    /// Helper function to create a Duplex command with commonly used test defaults.
    /// Uses sensible test defaults: disabled per-base tags, disabled overlapping consensus.
    fn create_duplex_with_paths(input: PathBuf, output: PathBuf) -> Duplex {
        Duplex {
            io: BamIoOptions {
                input,
                output,
                async_reader: false,
                check_crc: false,
                no_check_crc: false,
            },
            rejects_opts: RejectsOptions::default(),
            stats_opts: StatsOptions::default(),
            read_group: ReadGroupOptions {
                read_name_prefix: Some("consensus".to_string()),
                read_group_id: "duplex".to_string(),
            },
            consensus: ConsensusCallingOptions {
                output_per_base_tags: false,
                min_consensus_base_quality: 0,
                ..ConsensusCallingOptions::default()
            },
            overlapping: OverlappingConsensusOptions::default(),
            threading: ThreadingOptions::none(),
            compression: CompressionOptions { compression_level: 1 },
            min_reads: vec![1],
            max_reads_per_strand: None,
            allow_unmapped: AllowUnmappedOptions { enabled: false },
            scheduler_opts: SchedulerOptions::default(),
            queue_memory: QueueMemoryOptions::default(),
            methylation_mode: None,
            reference: None,
        }
    }

    // ========================================================================
    // Test Helper Functions
    // ========================================================================

    /// Create a test header with reference sequences
    fn create_test_header() -> sam::Header {
        use noodles::sam::header::record::value::map::Program;

        let builder = sam::Header::builder()
            .set_header(Map::default())
            .add_program("fgumi", Map::<Program>::default())
            .add_reference_sequence(
                "chr1",
                Map::<ReferenceSequence>::new(
                    NonZeroUsize::new(248_956_422).expect("non-zero chromosome length"),
                ),
            );

        // Consensus callers require template-coordinate-sorted input (CONS-01).
        fgumi_sam::header_as_template_coordinate(&builder.build())
    }

    fn to_record_buf(raw: fgumi_raw_bam::RawRecord) -> sam::alignment::RecordBuf {
        raw_record_to_record_buf(&raw, &sam::Header::default())
            .expect("raw_record_to_record_buf failed in test")
    }

    /// Build a test read with common parameters
    #[allow(clippy::cast_sign_loss)]
    fn build_test_read(
        name: &str,
        ref_id: usize,
        pos: i32,
        mapq: u8,
        raw_flags: u16,
        bases: &[u8],
    ) -> sam::alignment::RecordBuf {
        let cigar = encode_op(0, bases.len());
        let qual = vec![40u8; bases.len()];

        let mut b = RawSamBuilder::new();
        b.read_name(name.as_bytes())
            .flags(raw_flags)
            .ref_id(ref_id as i32)
            .pos(pos - 1)
            .mapq(mapq)
            .cigar_ops(&[cigar])
            .sequence(bases)
            .qualities(&qual);
        to_record_buf(b.build())
    }

    /// Create a pair of reads with MI tag
    #[allow(clippy::cast_sign_loss, clippy::too_many_arguments)]
    fn build_duplex_pair(
        name: &str,
        ref_id: usize,
        pos1: i32,
        pos2: i32,
        mi_tag: &str,
        bases: &[u8],
        rx_tag: Option<&str>,
        cell_tag: Option<&str>,
    ) -> (sam::alignment::RecordBuf, sam::alignment::RecordBuf) {
        let cigar = encode_op(0, bases.len());
        let qual = vec![40u8; bases.len()];

        let mut b1 = RawSamBuilder::new();
        b1.read_name(name.as_bytes())
            .flags(flags::PAIRED | flags::FIRST_SEGMENT | flags::MATE_REVERSE)
            .ref_id(ref_id as i32)
            .pos(pos1 - 1)
            .mapq(60)
            .cigar_ops(&[cigar])
            .sequence(bases)
            .qualities(&qual)
            .mate_ref_id(ref_id as i32)
            .mate_pos(pos2 - 1);
        b1.add_string_tag(SamTag::MI, mi_tag.as_bytes());
        if let Some(rx) = rx_tag {
            b1.add_string_tag(SamTag::RX, rx.as_bytes());
        }
        if let Some(cell) = cell_tag {
            b1.add_string_tag(SamTag::CB, cell.as_bytes());
        }
        let r1 = to_record_buf(b1.build());

        let mut b2 = RawSamBuilder::new();
        b2.read_name(name.as_bytes())
            .flags(flags::PAIRED | flags::LAST_SEGMENT | flags::REVERSE)
            .ref_id(ref_id as i32)
            .pos(pos2 - 1)
            .mapq(60)
            .cigar_ops(&[cigar])
            .sequence(bases)
            .qualities(&qual)
            .mate_ref_id(ref_id as i32)
            .mate_pos(pos1 - 1);
        b2.add_string_tag(SamTag::MI, mi_tag.as_bytes());
        if let Some(rx) = rx_tag {
            b2.add_string_tag(SamTag::RX, rx.as_bytes());
        }
        if let Some(cell) = cell_tag {
            b2.add_string_tag(SamTag::CB, cell.as_bytes());
        }
        let r2 = to_record_buf(b2.build());

        (r1, r2)
    }

    /// Write records to a temporary BAM file
    fn create_test_bam(mut records: Vec<sam::alignment::RecordBuf>) -> Result<NamedTempFile> {
        let temp_file = NamedTempFile::new()?;
        let header = create_test_header();

        // Sort records by template coordinate as required by duplex consensus calling
        // Sort by: min(R1_pos, R2_pos), max(R1_pos, R2_pos), MI tag, read name
        records.sort_by_key(|r| {
            let pos = r.alignment_start().map_or(usize::MAX, usize::from);
            let mate_pos = r.mate_alignment_start().map_or(usize::MAX, usize::from);
            let min_pos = pos.min(mate_pos);
            let max_pos = pos.max(mate_pos);
            let mi_tag = noodles::sam::alignment::record::data::field::Tag::from([b'M', b'I']);
            let mi =
                if let Some(noodles::sam::alignment::record_buf::data::field::Value::String(s)) =
                    r.data().get(&mi_tag)
                {
                    String::from_utf8_lossy(&s.iter().copied().collect::<Vec<u8>>()).to_string()
                } else {
                    String::new()
                };
            let name = r.name().map(|n| n.to_vec()).unwrap_or_default();
            (min_pos, max_pos, mi, name)
        });

        let mut writer = create_bam_writer(temp_file.path(), &header, 1, 6)?;

        for record in records {
            writer.write_alignment_record(&header, &record)?;
        }

        drop(writer); // Ensure file is flushed
        Ok(temp_file)
    }

    /// Read all records from a BAM file
    fn read_bam_records(path: &std::path::Path) -> Result<Vec<sam::alignment::RecordBuf>> {
        let (mut reader, header) = create_bam_reader(path, 1)?;
        let mut records = Vec::new();

        for result in reader.records() {
            let record = result?;
            let record_buf =
                sam::alignment::RecordBuf::try_from_alignment_record(&header, &record)?;
            records.push(record_buf);
        }

        Ok(records)
    }

    /// Helper function to get a string tag from a record
    fn get_string_tag(record: &sam::alignment::RecordBuf, tag_name: &str) -> Option<String> {
        let tag_bytes = tag_name.as_bytes();
        let tag = Tag::from([tag_bytes[0], tag_bytes[1]]);

        record.data().get(&tag).and_then(|v| {
            if let Value::String(s) = v {
                Some(String::from_utf8_lossy(s).to_string())
            } else {
                None
            }
        })
    }

    /// Count unique MI tags (without /A or /B suffix)
    fn count_unique_mi_tags(records: &[sam::alignment::RecordBuf]) -> usize {
        let tags: HashSet<String> =
            records.iter().filter_map(|r| get_string_tag(r, "MI")).collect();
        tags.len()
    }

    // ========================================================================
    // Unit Tests for Duplex Configuration
    // ========================================================================

    /// DUP-01: fgbio's `CallDuplexConsensusReads` requires both Phred error rates > 0
    /// (`CallDuplexConsensusReads.scala:131-132`); Q0 => P(err)=1, which fgbio rejects.
    #[rstest]
    #[case::defaults_valid(45, 40, true)]
    #[case::zero_pre_umi_rejected(0, 40, false)]
    #[case::zero_post_umi_rejected(45, 0, false)]
    fn test_error_rate_validation(
        #[case] pre_umi: u8,
        #[case] post_umi: u8,
        #[case] expect_ok: bool,
    ) {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.consensus.error_rate_pre_umi = pre_umi;
        duplex.consensus.error_rate_post_umi = post_umi;
        assert_eq!(duplex.validate().is_ok(), expect_ok);
    }

    /// `validate()` applies exactly the rule fgbio does to `--min-reads`: no lower bound,
    /// but the values must be ordered high to low — each no larger than the one before it,
    /// after fgbio's `padTo(3, last)` fills the missing slots.
    ///
    /// The accepted cases guard against reintroducing the lower-bound rejection
    /// `validate()` used to apply. A 0 in the per-strand slots is fgbio's single-strand
    /// mode (`-M 1 1 0`), where a molecule seen on only one strand still yields a
    /// consensus; a total of 0 is equivalent to 1, since a group that reaches the check
    /// has at least one read.
    ///
    /// The rejected cases pin the ordering rule to `validate()` rather than to
    /// `DuplexConsensusCaller::new` alone. `--threads` mode builds its caller inside the
    /// pipeline's per-batch closure, after the output BAM exists, so an ordering violation
    /// caught only by the constructor would be a mid-run failure over a partial file
    /// instead of an argument error.
    #[rstest]
    #[case::single_zero(vec![0], true)]
    #[case::all_zero(vec![0, 0, 0], true)]
    #[case::zero_two_value_form(vec![0, 0], true)]
    #[case::single_one(vec![1], true)]
    #[case::descending(vec![3, 2, 1], true)]
    #[case::single_strand_mode(vec![1, 1, 0], true)]
    #[case::zero_both_strand_slots(vec![1, 0, 0], true)]
    #[case::zero_in_two_value_form(vec![3, 0], true)]
    #[case::equal_values(vec![2, 2, 2], true)]
    #[case::xy_above_total(vec![1, 2, 3], false)]
    #[case::yx_above_xy(vec![3, 1, 2], false)]
    #[case::xy_above_total_in_two_value_form(vec![1, 2], false)]
    #[case::empty(vec![], false)]
    #[case::too_many_values(vec![4, 3, 2, 1], false)]
    fn test_validate_min_reads(#[case] min_reads: Vec<usize>, #[case] expect_ok: bool) {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.min_reads = min_reads.clone();
        assert_eq!(
            duplex.validate().is_ok(),
            expect_ok,
            "validate() disagreed with the --min-reads contract for {min_reads:?}"
        );
    }

    /// A cap of zero empties every strand, so no consensus can be built from any molecule.
    /// fgbio failed deep in consensus calling with a bare `IllegalArgumentException`
    /// (`CallDuplexConsensusReads`, fixed in fulcrumgenomics/fgbio#1166); fgumi was quieter
    /// still — it exited 0 having written an empty BAM. simplex and codec already reject
    /// their equivalents, so this closes the gap.
    ///
    /// Only a lower bound is applied, matching fgbio, rather than simplex/codec's stronger
    /// `max >= min_reads`: duplex's `--min-reads` is a vector of up to three values with its
    /// own ordering rule, and a cap below it is already handled gracefully — `consensus_call`
    /// returns no consensus rather than panicking.
    #[rstest]
    #[case::zero_rejected(Some(0), false)]
    #[case::one_accepted(Some(1), true)]
    #[case::typical_accepted(Some(50), true)]
    #[case::unset_accepted(None, true)]
    fn test_validate_max_reads_per_strand(
        #[case] max_reads_per_strand: Option<usize>,
        #[case] expect_ok: bool,
    ) {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.max_reads_per_strand = max_reads_per_strand;
        assert_eq!(
            duplex.validate().is_ok(),
            expect_ok,
            "validate() disagreed with the --max-reads-per-strand contract for \
             {max_reads_per_strand:?}"
        );
    }

    /// fgbio validates `--max-reads-per-strand >= 1` because its option is an `Option[Int]`
    /// and so accepts negatives. fgumi's is an `Option<usize>`, so clap rejects a negative at
    /// parse time and `validate()` never sees it — the guard above only has to cover zero.
    ///
    /// Uses the attached `=-1` form and asserts the error *kind*, because both of those are
    /// what make this test about the field's type. With the space-separated form clap rejects a
    /// bare `-1` as a flag-shaped token (`UnknownArgument`) whatever the field type is, so that
    /// spelling passes identically for an `Option<i64>` — the very shape this docstring claims
    /// would need a runtime guard.
    #[test]
    fn test_negative_max_reads_per_strand_fails_to_parse() {
        let parsed = Duplex::try_parse_from([
            "duplex",
            "--input",
            "in.bam",
            "--output",
            "out.bam",
            "--max-reads-per-strand=-1",
        ]);
        let error = parsed.expect_err("a negative --max-reads-per-strand must fail at parse time");
        assert_eq!(
            error.kind(),
            clap::error::ErrorKind::ValueValidation,
            "the value must be rejected by the `usize` parser, not as an unknown argument"
        );
    }

    #[test]
    fn test_default_parameters() {
        let duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));

        assert_eq!(duplex.min_reads, vec![1]);
        assert_eq!(duplex.consensus.min_input_base_quality, 10);
        assert!(duplex.threading.is_single_threaded());
        assert!(!duplex.consensus.trim);
    }

    #[test]
    fn test_custom_min_reads_single_value() {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.min_reads = vec![5];

        assert_eq!(duplex.min_reads, vec![5]);
    }

    #[test]
    fn test_custom_min_reads_three_values() {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.min_reads = vec![10, 5, 3];

        assert_eq!(duplex.min_reads, vec![10, 5, 3]);
    }

    #[test]
    fn test_output_per_base_tags_enabled() {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.consensus.output_per_base_tags = true;

        assert!(duplex.consensus.output_per_base_tags);
    }

    #[test]
    fn test_multithreaded_configuration() {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.threading = ThreadingOptions::new(8);

        assert_eq!(duplex.threading.threads, Some(8));
    }

    #[test]
    fn test_trim_and_downsample_options() {
        let mut duplex =
            create_duplex_with_paths(PathBuf::from("test.bam"), PathBuf::from("output.bam"));
        duplex.consensus.trim = true;
        duplex.max_reads_per_strand = Some(100);

        assert!(duplex.consensus.trim);
        assert_eq!(duplex.max_reads_per_strand, Some(100));
    }

    // ========================================================================
    // Integration Tests for Duplex Consensus Calling
    // ========================================================================

    #[test]
    fn test_duplex_consensus_basic_ab_ba_pairing() -> Result<()> {
        // Test basic duplex consensus from matching AB and BA strand groups
        // Following Scala test pattern: 1 A pair and 1 B pair
        let mut records = Vec::new();

        // A reads: R1 at 100 (forward), R2 at 200 (reverse) - query name "q1"
        let (r1_a, r2_a) =
            build_duplex_pair("q1", 0, 100, 200, "1/A", b"AAAAAAAAAA", Some("AAT-CCG"), None);
        records.push(r1_a);
        records.push(r2_a);

        // B reads: R1 at 200 (reverse), R2 at 100 (forward) - query name "q2", positions swapped
        let flags1 = 0x53; // paired, proper pair, first in pair, reverse
        let flags2 = 0x83; // paired, proper pair, second in pair, forward
        let mut r1_b = build_test_read("q2", 0, 200, 60, flags1, b"TTTTTTTTTT"); // Reverse complement of A
        let mut r2_b = build_test_read("q2", 0, 100, 60, flags2, b"AAAAAAAAAA");

        // Set mate info
        *r1_b.mate_reference_sequence_id_mut() = Some(0);
        *r1_b.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();
        *r2_b.mate_reference_sequence_id_mut() = Some(0);
        *r2_b.mate_alignment_start_mut() = noodles::core::Position::try_from(200_usize).ok();

        let mi = Tag::from([b'M', b'I']);
        r1_b.data_mut().insert(mi, Value::String(b"1/B".into()));
        r2_b.data_mut().insert(mi, Value::String(b"1/B".into()));

        let rx = Tag::from([b'R', b'X']);
        r1_b.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));
        r2_b.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));

        records.push(r1_b);
        records.push(r2_b);

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());

        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;

        // Should produce 2 consensus reads (R1 and R2 of the duplex consensus)
        assert_eq!(output_records.len(), 2, "Should have 2 duplex consensus reads");

        // Check that MI tags no longer have /A or /B suffix
        for record in &output_records {
            let mi = get_string_tag(record, "MI");
            assert!(mi.is_some(), "MI tag should be present");
            let mi = mi.expect("MI tag should have a value");
            assert_eq!(mi, "1", "MI tag should be '1' without /A or /B suffix");
        }

        // Check that RX tags are preserved
        for record in &output_records {
            let rx = get_string_tag(record, "RX");
            assert!(rx.is_some(), "RX tag should be preserved");
        }

        Ok(())
    }

    /// Builds an unmapped read (no reference, no position) carrying an MI tag,
    /// for exercising the `--allow-unmapped` pre-group filter gate.
    fn build_unmapped_read(
        name: &str,
        raw_flags: u16,
        mi: &str,
        bases: &[u8],
        rx: &str,
    ) -> sam::alignment::RecordBuf {
        let qual = vec![40u8; bases.len()];
        let mut b = RawSamBuilder::new();
        b.read_name(name.as_bytes())
            .flags(raw_flags | flags::UNMAPPED | flags::MATE_UNMAPPED)
            .ref_id(-1)
            .pos(-1)
            .mapq(0)
            .cigar_ops(&[])
            .sequence(bases)
            .qualities(&qual);
        b.add_string_tag(SamTag::MI, mi.as_bytes());
        b.add_string_tag(SamTag::RX, rx.as_bytes());
        to_record_buf(b.build())
    }

    /// The `--allow-unmapped` flag gates the fgbio pre-group filter for duplex.
    /// The same AB/BA molecule as `test_duplex_consensus_basic_ab_ba_pairing`,
    /// but with every read unmapped: dropped by default (fgbio parity),
    /// consensus-called with `--allow-unmapped`. Covers both the single-threaded
    /// fast path and the multi-threaded pipeline path.
    #[rstest]
    #[case::fast_path(ThreadingOptions::none())]
    #[case::threaded(ThreadingOptions::new(2))]
    fn test_duplex_allow_unmapped_gates_pregroup_filter(
        #[case] threading: ThreadingOptions,
    ) -> Result<()> {
        let build_molecule = || {
            vec![
                // A strand (MI 1/A)
                build_unmapped_read(
                    "q1",
                    flags::PAIRED | flags::FIRST_SEGMENT,
                    "1/A",
                    b"AAAAAAAAAA",
                    "AAT-CCG",
                ),
                build_unmapped_read(
                    "q1",
                    flags::PAIRED | flags::LAST_SEGMENT | flags::REVERSE,
                    "1/A",
                    b"AAAAAAAAAA",
                    "AAT-CCG",
                ),
                // B strand (MI 1/B) — reverse-complement strand
                build_unmapped_read(
                    "q2",
                    flags::PAIRED | flags::FIRST_SEGMENT | flags::REVERSE,
                    "1/B",
                    b"TTTTTTTTTT",
                    "CCG-AAT",
                ),
                build_unmapped_read(
                    "q2",
                    flags::PAIRED | flags::LAST_SEGMENT,
                    "1/B",
                    b"AAAAAAAAAA",
                    "CCG-AAT",
                ),
            ]
        };

        // Default: the pre-group filter drops the unmapped reads -> no consensus.
        let default_input = create_test_bam(build_molecule())?;
        let default_paths = TestPaths::new()?;
        let mut default_cmd = create_duplex_with_paths(
            default_input.path().to_path_buf(),
            default_paths.output.clone(),
        );
        default_cmd.threading = threading.clone();
        default_cmd.allow_unmapped.enabled = false;
        default_cmd.execute("test")?;
        let default_records = read_bam_records(&default_paths.output)?;
        assert!(
            default_records.is_empty(),
            "default (fgbio parity) drops unmapped reads before duplex consensus"
        );

        // --allow-unmapped: the unmapped molecule is consensus-called (duplex
        // emits R1 + R2 = 2 records).
        let allow_input = create_test_bam(build_molecule())?;
        let allow_paths = TestPaths::new()?;
        let mut allow_cmd =
            create_duplex_with_paths(allow_input.path().to_path_buf(), allow_paths.output.clone());
        allow_cmd.threading = threading;
        allow_cmd.allow_unmapped.enabled = true;
        allow_cmd.execute("test")?;
        let allow_records = read_bam_records(&allow_paths.output)?;
        assert_eq!(
            allow_records.len(),
            2,
            "--allow-unmapped consensus-calls the unmapped duplex molecule (R1 + R2)"
        );

        Ok(())
    }

    /// The `--allow-unmapped` CLI flag defaults to `false` (fgbio parity).
    #[test]
    fn test_duplex_allow_unmapped_defaults_to_false() {
        let default_cmd =
            <Duplex as clap::Parser>::try_parse_from(["duplex", "-i", "in.bam", "-o", "out.bam"])
                .expect("duplex should parse with only the required args");
        assert!(!default_cmd.allow_unmapped.enabled, "--allow-unmapped must default to false");

        let enabled_cmd = <Duplex as clap::Parser>::try_parse_from([
            "duplex",
            "-i",
            "in.bam",
            "-o",
            "out.bam",
            "--allow-unmapped",
        ])
        .expect("duplex should parse with --allow-unmapped");
        assert!(enabled_cmd.allow_unmapped.enabled, "bare --allow-unmapped must enable the flag");
    }

    #[test]
    fn test_duplex_no_consensus_when_strands_mismatched_r1() -> Result<()> {
        // Test that no consensus is generated when AB-R1s and BA-R2s are on different strands
        // (not properly complementary)
        let mut records = Vec::new();

        // AB reads: R1 forward (+), R2 forward (+) - WRONG!
        let (r1, mut r2) = build_duplex_pair("ab1", 0, 100, 200, "1/A", b"AAAAAAAAAA", None, None);
        // Make R2 forward instead of reverse
        let mut flags2 = r2.flags();
        flags2.set(noodles::sam::alignment::record::Flags::REVERSE_COMPLEMENTED, false);
        *r2.flags_mut() = flags2;
        records.push(r1);
        records.push(r2);

        // BA reads: R1 forward (+), R2 reverse (-) - correct orientation
        let flags1 = 0x53; // paired, first in pair, reverse
        let flags2 = 0x83; // paired, second in pair
        let mut r1 = build_test_read("ba1", 0, 200, 60, flags1, b"AAAAAAAAAA");
        let mut r2 = build_test_read("ba1", 0, 100, 60, flags2, b"AAAAAAAAAA");

        *r1.mate_reference_sequence_id_mut() = Some(0);
        *r1.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();
        *r2.mate_reference_sequence_id_mut() = Some(0);
        *r2.mate_alignment_start_mut() = noodles::core::Position::try_from(200_usize).ok();

        let mi = Tag::from([b'M', b'I']);
        r1.data_mut().insert(mi, Value::String(b"1/B".into()));
        r2.data_mut().insert(mi, Value::String(b"1/B".into()));

        records.push(r1);
        records.push(r2);

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());

        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;

        // Should produce 0 consensus reads due to strand mismatch
        assert_eq!(output_records.len(), 0, "Should have 0 consensus reads due to strand mismatch");

        Ok(())
    }

    #[test]
    fn test_duplex_with_min_reads_filtering() -> Result<()> {
        // Test that min-reads filtering works for AB and BA strands independently
        let mut records = Vec::new();

        // AB reads: 5 pairs (should pass min-reads=3)
        for i in 1..=5 {
            let (r1, r2) = build_duplex_pair(
                &format!("ab{i}"),
                0,
                100,
                100,
                "1/A",
                b"AAAAAAAAAA",
                Some("AAT-CCG"),
                None,
            );
            records.push(r1);
            records.push(r2);
        }

        // BA reads: 2 pairs (should fail min-reads=3)
        for i in 1..=2 {
            let flags1 = 0x53;
            let flags2 = 0x83;
            let mut r1 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags1, b"AAAAAAAAAA");
            let mut r2 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags2, b"AAAAAAAAAA");

            *r1.mate_reference_sequence_id_mut() = Some(0);
            *r1.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();
            *r2.mate_reference_sequence_id_mut() = Some(0);
            *r2.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();

            let mi = Tag::from([b'M', b'I']);
            r1.data_mut().insert(mi, Value::String(b"1/B".into()));
            r2.data_mut().insert(mi, Value::String(b"1/B".into()));

            let rx = Tag::from([b'R', b'X']);
            r1.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));
            r2.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));

            records.push(r1);
            records.push(r2);
        }

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let mut cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());
        cmd.min_reads = vec![3, 3, 3]; // duplex=3, AB=3, BA=3

        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;

        // BA strand has only 2 reads (< 3), so no duplex consensus should be generated
        assert_eq!(
            output_records.len(),
            0,
            "Should have 0 consensus reads because BA strand has insufficient reads"
        );

        Ok(())
    }

    #[test]
    fn test_duplex_with_per_base_tags() -> Result<()> {
        // Test that per-base tags are generated when enabled
        let mut records = Vec::new();

        // AB reads
        for i in 1..=3 {
            let (r1, r2) = build_duplex_pair(
                &format!("ab{i}"),
                0,
                100,
                100,
                "1/A",
                b"AAAAAAAAAA",
                Some("AAT-CCG"),
                None,
            );
            records.push(r1);
            records.push(r2);
        }

        // BA reads
        for i in 1..=3 {
            let flags1 = 0x53;
            let flags2 = 0x83;
            let mut r1 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags1, b"AAAAAAAAAA");
            let mut r2 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags2, b"AAAAAAAAAA");

            *r1.mate_reference_sequence_id_mut() = Some(0);
            *r1.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();
            *r2.mate_reference_sequence_id_mut() = Some(0);
            *r2.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();

            let mi = Tag::from([b'M', b'I']);
            r1.data_mut().insert(mi, Value::String(b"1/B".into()));
            r2.data_mut().insert(mi, Value::String(b"1/B".into()));

            let rx = Tag::from([b'R', b'X']);
            r1.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));
            r2.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));

            records.push(r1);
            records.push(r2);
        }

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let mut cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());
        cmd.consensus.output_per_base_tags = true; // Enable per-base tags

        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;
        assert_eq!(output_records.len(), 2, "Should have 2 consensus reads");

        // Check for per-base tags (ad, bd for depths)
        for record in &output_records {
            // At least one of the per-base depth tags should be present
            let has_ad = record.data().get(&Tag::from([b'a', b'd'])).is_some();
            let has_bd = record.data().get(&Tag::from([b'b', b'd'])).is_some();
            assert!(has_ad || has_bd, "Per-base tags should be present when enabled");
        }

        Ok(())
    }

    #[test]
    fn test_duplex_with_cell_barcode_preservation() -> Result<()> {
        // Test that cell barcodes are preserved in duplex consensus reads
        let mut records = Vec::new();

        // AB reads with cell barcode
        for i in 1..=3 {
            let (r1, r2) = build_duplex_pair(
                &format!("ab{i}"),
                0,
                100,
                100,
                "1/A",
                b"AAAAAAAAAA",
                Some("AAT-CCG"),
                Some("CELLBC"),
            );
            records.push(r1);
            records.push(r2);
        }

        // BA reads with same cell barcode
        for i in 1..=3 {
            let flags1 = 0x53;
            let flags2 = 0x83;
            let mut r1 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags1, b"AAAAAAAAAA");
            let mut r2 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags2, b"AAAAAAAAAA");

            *r1.mate_reference_sequence_id_mut() = Some(0);
            *r1.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();
            *r2.mate_reference_sequence_id_mut() = Some(0);
            *r2.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();

            let mi = Tag::from([b'M', b'I']);
            r1.data_mut().insert(mi, Value::String(b"1/B".into()));
            r2.data_mut().insert(mi, Value::String(b"1/B".into()));

            let rx = Tag::from([b'R', b'X']);
            r1.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));
            r2.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));

            let cb = Tag::from([b'C', b'B']);
            r1.data_mut().insert(cb, Value::String(b"CELLBC".into()));
            r2.data_mut().insert(cb, Value::String(b"CELLBC".into()));

            records.push(r1);
            records.push(r2);
        }

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());

        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;
        assert_eq!(output_records.len(), 2, "Should have 2 consensus reads");

        // Check that cell barcode (CB) is preserved in the consensus output
        for record in &output_records {
            let cell_bc = get_string_tag(record, "CB");
            assert_eq!(cell_bc, Some("CELLBC".to_string()), "Cell barcode should be preserved");
        }

        Ok(())
    }

    #[test]
    fn test_duplex_multithreading_produces_same_results() -> Result<()> {
        // Test that single-threaded and multi-threaded processing produce the same results
        let mut records = Vec::new();

        // Create multiple duplex groups
        for group in 1..=3 {
            // AB reads
            for i in 1..=3 {
                let (r1, r2) = build_duplex_pair(
                    &format!("g{group}_ab{i}"),
                    0,
                    100 * group,
                    100 * group,
                    &format!("{group}/A"),
                    b"AAAAAAAAAA",
                    Some("AAT-CCG"),
                    None,
                );
                records.push(r1);
                records.push(r2);
            }

            // BA reads
            for i in 1..=3 {
                let flags1 = 0x53;
                let flags2 = 0x83;
                let mut r1 = build_test_read(
                    &format!("g{group}_ba{i}"),
                    0,
                    100 * group,
                    60,
                    flags1,
                    b"AAAAAAAAAA",
                );
                let mut r2 = build_test_read(
                    &format!("g{group}_ba{i}"),
                    0,
                    100 * group,
                    60,
                    flags2,
                    b"AAAAAAAAAA",
                );

                *r1.mate_reference_sequence_id_mut() = Some(0);
                *r1.mate_alignment_start_mut() =
                    noodles::core::Position::try_from((100 * group) as usize).ok();
                *r2.mate_reference_sequence_id_mut() = Some(0);
                *r2.mate_alignment_start_mut() =
                    noodles::core::Position::try_from((100 * group) as usize).ok();

                let mi = Tag::from([b'M', b'I']);
                r1.data_mut().insert(mi, Value::String(format!("{group}/B").as_bytes().into()));
                r2.data_mut().insert(mi, Value::String(format!("{group}/B").as_bytes().into()));

                let rx = Tag::from([b'R', b'X']);
                r1.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));
                r2.data_mut().insert(rx, Value::String(b"CCG-AAT".into()));

                records.push(r1);
                records.push(r2);
            }
        }

        // Test with 1 thread
        let input1 = create_test_bam(records.clone())?;
        let paths = TestPaths::new()?;

        let cmd1 = create_duplex_with_paths(input1.path().to_path_buf(), paths.output.clone());

        cmd1.execute("test")?;
        let output1_records = read_bam_records(&paths.output)?;

        // Test with 4 threads
        let input2 = create_test_bam(records)?;
        let output2_path = paths.output_n(2);

        let mut cmd2 = create_duplex_with_paths(input2.path().to_path_buf(), output2_path.clone());
        cmd2.threading = ThreadingOptions::new(4);

        cmd2.execute("test")?;
        let output2_records = read_bam_records(&output2_path)?;

        // Should produce the same number of consensus reads
        assert_eq!(
            output1_records.len(),
            output2_records.len(),
            "Single-threaded and multi-threaded should produce same number of reads"
        );

        // Should have 3 groups * 2 reads per group = 6 reads
        assert_eq!(output1_records.len(), 6, "Should have 6 consensus reads (3 duplex pairs)");

        // Check that we have 3 unique MI tags in both outputs
        assert_eq!(count_unique_mi_tags(&output1_records), 3, "Should have 3 unique MI tags");
        assert_eq!(count_unique_mi_tags(&output2_records), 3, "Should have 3 unique MI tags");

        Ok(())
    }

    #[test]
    fn test_duplex_only_one_strand_no_consensus() -> Result<()> {
        // Test that no duplex consensus is generated when only one strand (A or B) is present
        let mut records = Vec::new();

        // Only AB reads, no BA reads
        for i in 1..=5 {
            let (r1, r2) = build_duplex_pair(
                &format!("ab{i}"),
                0,
                100,
                100,
                "1/A",
                b"AAAAAAAAAA",
                Some("AAT-CCG"),
                None,
            );
            records.push(r1);
            records.push(r2);
        }

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());

        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;

        // Should produce 0 consensus reads because we need both A and B strands
        assert_eq!(
            output_records.len(),
            0,
            "Should have 0 consensus reads when only one strand is present"
        );

        Ok(())
    }

    /// Parameterized test for all threading modes.
    ///
    /// Tests:
    /// - `None`: Single-threaded fast path, no pipeline
    /// - `Some(1)`: Pipeline with 1 thread
    /// - `Some(2)`: Pipeline with 2 threads
    #[rstest]
    #[case::fast_path(ThreadingOptions::none())]
    #[case::pipeline_1(ThreadingOptions::new(1))]
    #[case::pipeline_2(ThreadingOptions::new(2))]
    fn test_threading_modes(#[case] threading: ThreadingOptions) -> Result<()> {
        // Create test data with A and B strand reads
        let mut records = Vec::new();

        // Create a group with A strand (MI=1/A) and B strand (MI=1/B) for duplex calling
        for i in 0..5 {
            let (r1, r2) = build_duplex_pair(
                &format!("a{i}"),
                0,
                100,
                200,
                "1/A",
                b"AAAAAAAAAA",
                Some("AAT-CCG"),
                None,
            );
            records.push(r1);
            records.push(r2);
        }
        for i in 0..5 {
            let (r1, r2) = build_duplex_pair(
                &format!("b{i}"),
                0,
                100,
                200,
                "1/B",
                b"AAAAAAAAAA",
                Some("AAT-CCG"),
                None,
            );
            records.push(r1);
            records.push(r2);
        }

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let mut cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());
        cmd.threading = threading;
        cmd.execute("test")?;

        // Should have at least some output (duplex consensus)
        assert!(&paths.output.exists());

        Ok(())
    }

    #[rstest]
    #[case::single_threaded(ThreadingOptions::none())]
    #[case::multi_threaded(ThreadingOptions::new(2))]
    fn test_duplex_em_seq_command(#[case] threading: ThreadingOptions) -> Result<()> {
        use std::io::Write;

        // Create a FASTA with chr1 containing C bases at the aligned region
        let ref_seq = "C".repeat(300);
        let ref_file = {
            let mut f = tempfile::NamedTempFile::new()?;
            writeln!(f, ">chr1")?;
            writeln!(f, "{ref_seq}")?;
            f.flush()?;
            f
        };

        // Create properly structured AB/BA duplex pairs
        let mut records = Vec::new();

        // AB reads: R1 forward at 100, R2 reverse at 100
        for i in 0..3 {
            let (r1, r2) =
                build_duplex_pair(&format!("ab{i}"), 0, 100, 100, "1/A", b"CCCCCCCCCC", None, None);
            records.push(r1);
            records.push(r2);
        }

        // BA reads: R1 reverse at 100, R2 forward at 100 (opposite strand orientation)
        for i in 0..3 {
            let flags1 = 0x53_u16; // paired, proper pair, first in pair, reverse
            let flags2 = 0x83_u16; // paired, proper pair, second in pair, forward
            let mut r1 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags1, b"CCCCCCCCCC");
            let mut r2 = build_test_read(&format!("ba{i}"), 0, 100, 60, flags2, b"CCCCCCCCCC");

            *r1.mate_reference_sequence_id_mut() = Some(0);
            *r1.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();
            *r2.mate_reference_sequence_id_mut() = Some(0);
            *r2.mate_alignment_start_mut() = noodles::core::Position::try_from(100_usize).ok();

            let mi = Tag::from([b'M', b'I']);
            r1.data_mut().insert(mi, Value::String(b"1/B".into()));
            r2.data_mut().insert(mi, Value::String(b"1/B".into()));

            records.push(r1);
            records.push(r2);
        }

        let input = create_test_bam(records)?;
        let paths = TestPaths::new()?;

        let mut cmd = create_duplex_with_paths(input.path().to_path_buf(), paths.output.clone());
        cmd.methylation_mode = Some(crate::commands::common::MethylationModeArg::EmSeq);
        cmd.reference = Some(ref_file.path().to_path_buf());
        cmd.threading = threading;
        cmd.execute("test")?;

        let output_records = read_bam_records(&paths.output)?;
        assert_eq!(output_records.len(), 2, "Should have 2 duplex consensus reads");

        // Verify methylation tags are present on output reads
        for record in &output_records {
            let cu_tag = Tag::from([b'c', b'u']);
            assert!(record.data().get(&cu_tag).is_some(), "cu tag should be present with EM-Seq");
            let ct_tag = Tag::from([b'c', b't']);
            assert!(record.data().get(&ct_tag).is_some(), "ct tag should be present with EM-Seq");
        }

        Ok(())
    }
}
