//! Shared types and functions for metrics commands (duplex-metrics, simplex-metrics).
//!
//! This module contains the common infrastructure for reading UMI-grouped BAM files,
//! grouping templates by coordinate, filtering by genomic intervals, and performing
//! deterministic downsampling. Both `duplex_metrics` and `simplex_metrics` commands
//! build on these shared primitives.

use crate::bam_io::{create_bam_reader, create_raw_bam_reader};
use crate::sam::SamTag;
use crate::template::TemplateIterator;
use anyhow::{Context, Result};
use fgumi_raw_bam::{AsTagBytes, RawRecord, find_string_tag_in_record};

use std::path::Path;
use std::sync::OnceLock;
use tracing::info;

// Re-export types and functions that have been moved to fgumi-metrics.
pub use fgumi_metrics::{
    DOWNSAMPLING_FRACTIONS, Interval, ReadInfoKey, TemplateInfo, TemplateMetadata,
    compute_hash_fraction, compute_template_metadata, overlaps_intervals, parse_intervals,
};

/// Cached R availability check (computed once per process).
static R_AVAILABLE: OnceLock<bool> = OnceLock::new();

/// Computes the unclipped 5' position for a read, matching fgbio's `positionOf`.
///
/// For forward strand reads: `unclippedStart = alignmentStart - leading soft clips`
/// For reverse strand reads: `unclippedEnd = alignmentEnd + trailing soft clips`
///
/// Returns `None` for unmapped reads.
pub fn unclipped_five_prime_position(record: &fgumi_raw_bam::RawRecord) -> Option<i32> {
    if record.is_unmapped() {
        return None;
    }
    Some(fgumi_raw_bam::unclipped_5prime_from_raw_bam(record.as_ref()))
}

/// Validates that a BAM file is not a consensus BAM.
///
/// Consensus BAMs (output from simplex/duplex callers) should not be used with
/// metrics tools. This checks the first valid R1 record and errors if it contains
/// consensus tags.
///
/// # Errors
///
/// Returns an error if the BAM file cannot be read or if it appears to be a consensus BAM.
pub fn validate_not_consensus_bam(input: &Path) -> Result<()> {
    use crate::consensus_tags::is_consensus;

    let (mut reader, header) = create_bam_reader(input, 1)?;

    // Look at the first valid R1 record
    for result in reader.record_bufs(&header) {
        let record = result?;

        // Only check R1 records that are paired, mapped, and primary
        let flags = record.flags();
        if !flags.is_segmented()
            || !flags.is_first_segment()
            || flags.is_secondary()
            || flags.is_supplementary()
            || flags.is_unmapped()
        {
            continue;
        }

        // Check if this is a consensus read
        if is_consensus(&record) {
            anyhow::bail!(
                "Input BAM file ({}) appears to contain consensus sequences. \
                This metrics tool cannot run on consensus BAMs, and instead requires \
                the UMI-grouped BAM generated by group which is run prior to consensus calling.\n\
                First R1 record '{}' has consensus SAM tags present.",
                input.display(),
                record.name().map_or_else(
                    || "<unnamed>".to_string(),
                    |n| String::from_utf8_lossy(n.as_ref()).to_string()
                )
            );
        }

        // Only need to check the first valid R1 record
        break;
    }

    Ok(())
}

/// Checks if R and required packages (ggplot2, scales) are available.
///
/// Result is cached for the lifetime of the process to avoid repeated subprocess spawns.
pub fn is_r_available() -> bool {
    use std::process::Command;

    *R_AVAILABLE.get_or_init(|| {
        Command::new("Rscript")
            .args(["-e", "stopifnot(require(ggplot2)); stopifnot(require(scales))"])
            .output()
            .map(|output| output.status.success())
            .unwrap_or(false)
    })
}

/// Executes an R script with the given arguments.
///
/// The R script content is written to a temporary file for execution. This ensures
/// the script is always available regardless of working directory or installation
/// location.
///
/// # Arguments
///
/// * `r_script_content` - The R script source code to execute
/// * `args` - Command-line arguments to pass to the R script
/// * `temp_file_name` - Base name for the temporary R script file
///
/// # Errors
///
/// Returns an error if the script cannot be written or R execution fails.
pub fn execute_r_script(r_script_content: &str, args: &[&str], temp_file_name: &str) -> Result<()> {
    use std::process::Command;

    // Write embedded R script to temp file
    let temp_dir = std::env::temp_dir();
    let r_script_path = temp_dir.join(temp_file_name);
    std::fs::write(&r_script_path, r_script_content)
        .context("Failed to write embedded R script to temp file")?;

    info!("Executing R script to generate PDF plots...");

    let output = Command::new("Rscript")
        .arg(&r_script_path)
        .args(args)
        .output()
        .context("Failed to execute Rscript command")?;

    // Clean up temp file (ignore errors)
    let _ = std::fs::remove_file(&r_script_path);

    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!(
            "R script execution failed with exit code {:?}. Error: {}",
            output.status.code(),
            stderr
        )
    }
}

/// Reads a BAM file, groups templates by [`ReadInfoKey`], and calls a closure for each group.
///
/// This is the shared BAM processing loop used by both duplex-metrics and simplex-metrics.
/// Templates are streamed in coordinate order; when the [`ReadInfoKey`] changes, the
/// accumulated group is dispatched to the closure.
///
/// # Arguments
///
/// * `input` - Path to the input BAM file
/// * `intervals` - Intervals for filtering templates (empty = no filtering)
/// * `num_fractions` - Number of downsampling fractions (used to size the counts vector)
/// * `process_group` - Closure called for each coordinate group with `(group, fraction_counts)`
///
/// The SAM spec standard tags `MI` and `RX` are always used.
///
/// # Returns
///
/// A tuple of `(total_template_count, per_fraction_template_counts)`.
///
/// # Errors
///
/// Returns an error if the BAM file cannot be read, if required `MI`/`RX` tags
/// are missing on qualifying templates, or if tag values are invalid UTF-8.
pub fn process_templates_from_bam<F>(
    input: &Path,
    intervals: &[Interval],
    num_fractions: usize,
    mut process_group: F,
) -> Result<(usize, Vec<usize>)>
where
    F: FnMut(&[TemplateInfo], &mut Vec<usize>),
{
    let (reader, header) = create_raw_bam_reader(input, 1)?;
    let template_iter = TemplateIterator::new(reader);

    // Streaming approach: process groups as they arrive (assumes consecutive ReadInfo grouping)
    let mut current_group: Vec<TemplateInfo> = Vec::new();
    let mut current_key: Option<ReadInfoKey> = None;
    let mut template_count = 0;
    let mut fraction_template_counts: Vec<usize> = vec![0; num_fractions];

    for template in template_iter {
        let template = template?;
        if template.records.len() < 2 {
            continue;
        }

        // Find R1 and R2 that pass fgbio's filtering criteria
        use fgumi_raw_bam::flags as raw_flags;
        let is_r1_r2_candidate = |f: u16, first: bool| {
            (f & raw_flags::PAIRED) != 0
                && (f & raw_flags::UNMAPPED) == 0
                && (f & raw_flags::MATE_UNMAPPED) == 0
                && ((f & raw_flags::FIRST_SEGMENT) != 0) == first
                && ((f & raw_flags::LAST_SEGMENT) != 0) != first
                && (f & raw_flags::SECONDARY) == 0
                && (f & raw_flags::SUPPLEMENTARY) == 0
        };
        let r1 = template.records.iter().find(|r| is_r1_r2_candidate(r.flags(), true));
        let r2 = template.records.iter().find(|r| is_r1_r2_candidate(r.flags(), false));

        let (r1, r2) = match (r1, r2) {
            (Some(r1), Some(r2)) => (r1, r2),
            _ => continue,
        };

        // Get read name
        let read_name =
            String::from_utf8_lossy(fgumi_raw_bam::fields::read_name(r1.as_ref())).to_string();

        let mi = required_z_tag(r1, SamTag::MI, &read_name)?;
        let rx = required_z_tag(r1, SamTag::RX, &read_name)?;

        // Helper: reference_sequence_id() on RawRecord -> Option<usize>
        // (main's fields::ref_id returns i32, with -1 for unmapped).
        let ref_id_of = |bam: &[u8]| -> Option<usize> {
            let r = fgumi_raw_bam::fields::ref_id(bam);
            if r < 0 { None } else { Some(r as usize) }
        };

        // Get reference position and calculate insert coordinates
        let ref_name = if let Some(ref_id) = ref_id_of(r1.as_ref()) {
            header.reference_sequences().get_index(ref_id).map(|(name, _)| name.to_string())
        } else {
            None
        };

        // Calculate insert coordinates and ReadInfo key (matching fgbio)
        let (position, end_position, read_info_key) = {
            let r1_ref = ref_id_of(r1.as_ref());
            let r2_ref = ref_id_of(r2.as_ref());

            if r1_ref == r2_ref && r1_ref.is_some() {
                // Get unclipped 5' positions (matching fgbio's positionOf)
                let r1_5prime = unclipped_five_prime_position(r1);
                let r2_5prime = unclipped_five_prime_position(r2);
                let r1_strand = (r1.flags() & fgumi_raw_bam::flags::REVERSE) != 0;
                let r2_strand = (r2.flags() & fgumi_raw_bam::flags::REVERSE) != 0;

                if let (Some(s1), Some(s2)) = (r1_5prime, r2_5prime) {
                    // For insert coordinates, use alignment positions
                    let r1_start =
                        fgumi_raw_bam::alignment_start_from_raw(r1.as_ref()).map(|p| p as i32);
                    let r2_start =
                        fgumi_raw_bam::alignment_start_from_raw(r2.as_ref()).map(|p| p as i32);
                    let r1_end =
                        fgumi_raw_bam::alignment_end_from_raw(r1.as_ref()).map(|p| p as i32);
                    let r2_end =
                        fgumi_raw_bam::alignment_end_from_raw(r2.as_ref()).map(|p| p as i32);

                    let (pos, end) = match (r1_start, r2_start, r1_end, r2_end) {
                        (Some(rs1), Some(rs2), Some(re1), Some(re2)) => {
                            (rs1.min(rs2), re1.max(re2))
                        }
                        (Some(rs1), Some(rs2), _, _) => (rs1.min(rs2), rs1.max(rs2)),
                        _ => continue,
                    };

                    // Build ReadInfo key: order by (ref, 5' position) so earlier read is first
                    let key = if (r1_ref, s1) <= (r2_ref, s2) {
                        ReadInfoKey {
                            ref_index1: r1_ref,
                            start1: s1,
                            strand1: r1_strand,
                            ref_index2: r2_ref,
                            start2: s2,
                            strand2: r2_strand,
                        }
                    } else {
                        ReadInfoKey {
                            ref_index1: r2_ref,
                            start1: s2,
                            strand1: r2_strand,
                            ref_index2: r1_ref,
                            start2: s1,
                            strand2: r1_strand,
                        }
                    };

                    (pos, end, key)
                } else {
                    continue;
                }
            } else {
                continue;
            }
        };

        // Compute hash once for this template
        let hash_fraction = compute_hash_fraction(&read_name);

        let template_info = TemplateInfo {
            mi,
            rx,
            ref_name,
            position: Some(position),
            end_position: Some(end_position),
            hash_fraction,
            read_info_key: read_info_key.clone(),
        };

        // Check interval overlap
        if !overlaps_intervals(
            template_info.ref_name.as_deref(),
            template_info.position,
            template_info.end_position,
            intervals,
        ) {
            continue;
        }

        template_count += 1;
        crate::progress::records_out("shared_metrics", 2); // Each template has R1 and R2

        // Streaming: when ReadInfo key changes, process the accumulated group
        if current_key.as_ref() != Some(&read_info_key) && !current_group.is_empty() {
            process_group(&current_group, &mut fraction_template_counts);
            current_group.clear();
        }

        current_group.push(template_info);
        current_key = Some(read_info_key);
    }

    // Process the final group
    if !current_group.is_empty() {
        process_group(&current_group, &mut fraction_template_counts);
    }

    Ok((template_count, fraction_template_counts))
}

/// Extracts a required Z-typed aux tag from `record`, returning an error that
/// points at `read_name` when the tag is absent or not UTF-8.
fn required_z_tag(record: &RawRecord, tag: impl AsTagBytes, read_name: &str) -> Result<String> {
    let tag_bytes = *tag.as_tag_bytes();
    let tag_name = std::str::from_utf8(&tag_bytes).unwrap_or("??");
    let bytes = find_string_tag_in_record(record.as_ref(), tag).ok_or_else(|| {
        anyhow::anyhow!(
            "Read '{read_name}' is missing the required {tag_name} tag. \
             Metrics commands require standard MI/RX tags."
        )
    })?;
    std::str::from_utf8(bytes)
        .map(str::to_string)
        .map_err(|e| anyhow::anyhow!("Read '{read_name}' {tag_name} tag is not UTF-8: {e}"))
}
