//! Consensus-related SAM tags for reads generated by consensus calling tools.
//!
//! This module encapsulates the various consensus related tags that are added to consensus reads
//! at both the per-read and per-base level.
//!
//! Contains tags for both single-strand and duplex consensus reads. The first letter in the tag is:
//! - `c` if it relates to the final consensus read
//! - `a` if it relates to the AB/top-strand of a duplex consensus read
//! - `b` if it relates to the BA/bottom-strand of a duplex consensus read
//!
//! The second letter in the tag is:
//! - Lower case if it is per-base
//! - Upper case if it is per-read
//!
//! ```text
//! Value                 AB  BA  Final
//! --------------------- --  --  -----
//! per-read-depth        aD  bD  cD
//! per-read-min-depth    aM  bM  cM
//! per-read-error-rate   aE  bE  cE
//! per-base-depth        ad  bd  cd
//! per-base-error-count  ae  be  ce
//! per-base-bases        ac  bc  bases
//! per-base-quals        aq  bq  quals
//! ```

use fgumi_sam::SamTag;
use noodles::sam::alignment::record_buf::data::field::value::Value;

/// Converts a sequence (`Vec<u8>`) to a String value for SAM tags.
///
/// This matches fgbio's format for ac/bc tags (Z string type).
#[must_use]
pub fn sequence_to_tag_value(bases: &[u8]) -> Value {
    Value::from(String::from_utf8_lossy(bases).to_string())
}

/// Converts quality scores (`Vec<u8>`) to an ASCII Phred+33 String value for SAM tags.
///
/// This matches fgbio's format for aq/bq tags (Z string type).
/// Each quality score is converted to its Phred+33 ASCII representation.
#[must_use]
pub fn qualities_to_tag_value(quals: &[u8]) -> Value {
    let ascii_quals: String = quals.iter().map(|&q| (q + 33) as char).collect();
    Value::from(ascii_quals)
}

/// Default field in which to look for UMI sequences (`RX`).
pub const UMI_BASES: SamTag = SamTag::RX;

/// Default field in which to look for UMI qualities (`QX`).
pub const UMI_QUALS: SamTag = SamTag::QX;

/// Field in which the original UMI bases are stored post-correction (`OX`).
pub const ORIGINAL_UMI_BASES: SamTag = SamTag::OX;

/// Field in which the original UMI qualities are stored post-correction (`BZ`).
pub const ORIGINAL_UMI_QUALS: SamTag = SamTag::BZ;

/// Post-grouping ID that is file-wide unique per source molecule (`MI`).
pub const MOLECULAR_ID: SamTag = SamTag::MI;

/// Per-base consensus tag aliases.
pub mod per_base {
    use super::SamTag;

    /// The per-base number of raw-reads contributing to the consensus (stored as a short[])
    pub const RAW_READ_COUNT: SamTag = SamTag::CD_BASES;

    /// The number of bases at each position that disagreed with the final consensus call (stored as a short[])
    /// If the final consensus call is a no call (N), then we use the most likely consensus base instead
    pub const RAW_READ_ERRORS: SamTag = SamTag::CE_BASES;

    /// The per-base number of raw reads contributing to the AB single-strand consensus
    pub const AB_RAW_READ_COUNT: SamTag = SamTag::AD_BASES;

    /// The per-base number of raw reads contributing to the BA single-strand consensus
    pub const BA_RAW_READ_COUNT: SamTag = SamTag::BD_BASES;

    /// The number of bases disagreeing with the AB single-strand consensus
    pub const AB_RAW_READ_ERRORS: SamTag = SamTag::AE_BASES;

    /// The number of bases disagreeing with the BA single-strand consensus
    pub const BA_RAW_READ_ERRORS: SamTag = SamTag::BE_BASES;

    /// The single-stranded consensus bases from the AB raw reads
    pub const AB_CONSENSUS_BASES: SamTag = SamTag::AC;

    /// The single-stranded consensus bases from the BA raw reads
    pub const BA_CONSENSUS_BASES: SamTag = SamTag::BC_BASES;

    /// The phred-scaled qualities (as phred-33 ascii values) of the AB single-strand consensus
    pub const AB_CONSENSUS_QUALS: SamTag = SamTag::AQ;

    /// The phred-scaled qualities (as phred-33 ascii values) of the BA single-strand consensus
    pub const BA_CONSENSUS_QUALS: SamTag = SamTag::BQ;

    /// Per-base count of unconverted bases (combined/simplex consensus)
    pub const UNCONVERTED_COUNT: SamTag = SamTag::CU;

    /// Per-base count of converted bases (combined/simplex consensus)
    pub const CONVERTED_COUNT: SamTag = SamTag::CT;

    /// Per-base count of unconverted bases (AB strand, duplex)
    pub const AB_UNCONVERTED_COUNT: SamTag = SamTag::AU;

    /// Per-base count of converted bases (AB strand, duplex)
    pub const AB_CONVERTED_COUNT: SamTag = SamTag::AT;

    /// Per-base count of unconverted bases (BA strand, duplex)
    pub const BA_UNCONVERTED_COUNT: SamTag = SamTag::BU;

    /// Per-base count of converted bases (BA strand, duplex)
    pub const BA_CONVERTED_COUNT: SamTag = SamTag::BT;

    /// All per-base consensus tags, including methylation counts. Delegates to [`SamTag::PER_BASE_CONSENSUS_TAGS`].
    pub const ALL_TAGS: &[SamTag] = SamTag::PER_BASE_CONSENSUS_TAGS;
    /// Per-base tags that must be reversed for negative-strand reads. Delegates to [`SamTag::PER_BASE_TAGS_TO_REVERSE`].
    pub const TAGS_TO_REVERSE: &[SamTag] = SamTag::PER_BASE_TAGS_TO_REVERSE;
    /// Per-base tags that must be reverse-complemented for negative-strand reads. Delegates to [`SamTag::PER_BASE_TAGS_TO_REVCOMP`].
    pub const TAGS_TO_REVERSE_COMPLEMENT: &[SamTag] = SamTag::PER_BASE_TAGS_TO_REVCOMP;

    /// Returns all per-base consensus tags
    #[must_use]
    pub fn all_tags() -> &'static [SamTag] {
        ALL_TAGS
    }

    /// Returns all per-base tags that need to be reversed for negative-strand reads
    #[must_use]
    pub fn tags_to_reverse() -> &'static [SamTag] {
        TAGS_TO_REVERSE
    }

    /// Returns all per-base tags that need to be reverse complemented for negative-strand reads
    #[must_use]
    pub fn tags_to_reverse_complement() -> &'static [SamTag] {
        TAGS_TO_REVERSE_COMPLEMENT
    }
}

/// Per-read consensus tag aliases.
pub mod per_read {
    use super::SamTag;

    /// The number of raw reads that contributed to the consensus (max of per-base counts)
    pub const RAW_READ_COUNT: SamTag = SamTag::CD;

    /// The minimum number of raw reads contributing to a consensus call anywhere in the read
    pub const MIN_RAW_READ_COUNT: SamTag = SamTag::CM;

    /// The fraction of bases in raw reads that disagreed with the consensus call
    pub const RAW_READ_ERROR_RATE: SamTag = SamTag::CE;

    /// The max depth of raw reads contributing to the AB single-strand consensus
    pub const AB_RAW_READ_COUNT: SamTag = SamTag::AD;

    /// The max depth of raw reads contributing to the BA single-strand consensus
    pub const BA_RAW_READ_COUNT: SamTag = SamTag::BD;

    /// The min depth of raw reads contributing to the AB single-strand consensus
    pub const AB_MIN_RAW_READ_COUNT: SamTag = SamTag::AM;

    /// The min depth of raw reads contributing to the BA single-strand consensus
    pub const BA_MIN_RAW_READ_COUNT: SamTag = SamTag::BM;

    /// The error rate for the AB single-strand consensus
    pub const AB_RAW_READ_ERROR_RATE: SamTag = SamTag::AE;

    /// The error rate for the BA single-strand consensus
    pub const BA_RAW_READ_ERROR_RATE: SamTag = SamTag::BE;

    /// All per-read consensus tags. Delegates to [`SamTag::PER_READ_CONSENSUS_TAGS`].
    pub const ALL_TAGS: &[SamTag] = SamTag::PER_READ_CONSENSUS_TAGS;

    /// Returns all per-read consensus tags
    #[must_use]
    pub fn all_tags() -> &'static [SamTag] {
        ALL_TAGS
    }
}

/// Checks if a read appears to be a simplex consensus read.
///
/// A simplex consensus read has the `cD` (`RawReadCount`) tag but NOT the duplex tags (`aD` and `bD`).
#[must_use]
pub fn is_simplex_consensus(rec: &impl noodles::sam::alignment::Record) -> bool {
    let has_cd = rec.data().get(&SamTag::CD.to_noodles_tag()).is_some();
    has_cd && !is_duplex_consensus(rec)
}

/// Checks if a read appears to be a duplex consensus read.
///
/// A duplex consensus read has both the `aD` (`AbRawReadCount`) and `bD` (`BaRawReadCount`) tags.
#[must_use]
#[expect(
    clippy::similar_names,
    reason = "aD/bD tag names are domain-specific duplex strand identifiers"
)]
pub fn is_duplex_consensus(rec: &impl noodles::sam::alignment::Record) -> bool {
    let has_ad = rec.data().get(&SamTag::AD.to_noodles_tag()).is_some();
    let has_bd = rec.data().get(&SamTag::BD.to_noodles_tag()).is_some();
    has_ad && has_bd
}

/// Checks if a read appears to be any kind of consensus read (simplex or duplex).
///
/// This matches fgbio's `Umis.isFgbioStyleConsensus()` function.
#[must_use]
pub fn is_consensus(rec: &impl noodles::sam::alignment::Record) -> bool {
    is_simplex_consensus(rec) || is_duplex_consensus(rec)
}

#[cfg(test)]
mod tests {
    use super::*;
    use fgumi_raw_bam::{RawRecord, SamBuilder, raw_record_to_record_buf};

    /// Build a minimal `RawRecord` with the given integer tags, then decode to
    /// `RecordBuf` so that `is_*_consensus` (which takes `&impl Record`) can be tested.
    fn make_record_with_int_tags(tags: &[(SamTag, i32)]) -> impl noodles::sam::alignment::Record {
        let mut b = SamBuilder::new();
        b.sequence(b"ACGT").qualities(&[30u8; 4]);
        for (tag, value) in tags {
            b.add_int_tag(*tag, *value);
        }
        let raw: RawRecord = b.build();
        raw_record_to_record_buf(&raw, &noodles::sam::Header::default()).expect("decode failed")
    }

    /// Build a minimal `RawRecord` with the given string tags, then decode to `RecordBuf`.
    fn make_record_with_str_tags(tags: &[(SamTag, &[u8])]) -> impl noodles::sam::alignment::Record {
        let mut b = SamBuilder::new();
        b.sequence(b"ACGT").qualities(&[30u8; 4]);
        for (tag, value) in tags {
            b.add_string_tag(*tag, value);
        }
        let raw: RawRecord = b.build();
        raw_record_to_record_buf(&raw, &noodles::sam::Header::default()).expect("decode failed")
    }

    #[test]
    fn test_tag_constants() {
        assert_eq!(UMI_BASES, fgumi_sam::SamTag::RX);
        assert_eq!(MOLECULAR_ID, fgumi_sam::SamTag::MI);
        assert_eq!(per_base::RAW_READ_COUNT, fgumi_sam::SamTag::CD_BASES);
        assert_eq!(per_read::RAW_READ_COUNT, fgumi_sam::SamTag::CD);
    }

    #[test]
    fn test_per_base_tags() {
        let tags = per_base::all_tags();
        assert!(tags.contains(&fgumi_sam::SamTag::CD_BASES));
        assert!(tags.contains(&fgumi_sam::SamTag::CE_BASES));
        assert!(tags.contains(&fgumi_sam::SamTag::AD_BASES));
        assert!(tags.contains(&fgumi_sam::SamTag::BD_BASES));
        assert!(tags.contains(&fgumi_sam::SamTag::AC));
        assert!(tags.contains(&fgumi_sam::SamTag::BC_BASES));
    }

    #[test]
    fn test_per_read_tags() {
        let tags = per_read::all_tags();
        assert!(tags.contains(&fgumi_sam::SamTag::CD));
        assert!(tags.contains(&fgumi_sam::SamTag::CM));
        assert!(tags.contains(&fgumi_sam::SamTag::CE));
        assert!(tags.contains(&fgumi_sam::SamTag::AD));
        assert!(tags.contains(&fgumi_sam::SamTag::BD));
    }

    #[test]
    fn test_is_simplex_consensus() {
        // Create a record with cD tag (simplex consensus)
        let rec = make_record_with_int_tags(&[(SamTag::CD, 10)]);

        assert!(is_simplex_consensus(&rec));
        assert!(!is_duplex_consensus(&rec));
        assert!(is_consensus(&rec));
    }

    #[test]
    fn test_is_duplex_consensus() {
        // Create a record with aD and bD tags (duplex consensus)
        let rec = make_record_with_int_tags(&[(SamTag::AD, 10), (SamTag::BD, 5)]);

        assert!(!is_simplex_consensus(&rec));
        assert!(is_duplex_consensus(&rec));
        assert!(is_consensus(&rec));
    }

    #[test]
    fn test_is_not_consensus() {
        // Create a record without consensus tags (raw read)
        let rec = make_record_with_str_tags(&[(SamTag::RX, b"ACGT")]);

        assert!(!is_simplex_consensus(&rec));
        assert!(!is_duplex_consensus(&rec));
        assert!(!is_consensus(&rec));
    }

    // =====================================================================
    // Tests for sequence_to_tag_value and qualities_to_tag_value
    // =====================================================================

    #[test]
    fn test_sequence_to_tag_value() {
        let bases = b"ACGT";
        let value = sequence_to_tag_value(bases);
        match value {
            noodles::sam::alignment::record_buf::data::field::value::Value::String(s) => {
                assert_eq!(s, "ACGT");
            }
            _ => panic!("Expected String value"),
        }
    }

    #[test]
    fn test_sequence_to_tag_value_empty() {
        let bases = b"";
        let value = sequence_to_tag_value(bases);
        match value {
            noodles::sam::alignment::record_buf::data::field::value::Value::String(s) => {
                assert_eq!(s, "");
            }
            _ => panic!("Expected String value"),
        }
    }

    #[test]
    fn test_qualities_to_tag_value() {
        // Q0 -> '!' (33), Q10 -> '+' (43), Q30 -> '?' (63)
        let quals = vec![0, 10, 30];
        let value = qualities_to_tag_value(&quals);
        match value {
            noodles::sam::alignment::record_buf::data::field::value::Value::String(s) => {
                assert_eq!(&**s, &[33, 43, 63]);
            }
            _ => panic!("Expected String value"),
        }
    }

    #[test]
    fn test_qualities_to_tag_value_empty() {
        let quals: Vec<u8> = vec![];
        let value = qualities_to_tag_value(&quals);
        match value {
            noodles::sam::alignment::record_buf::data::field::value::Value::String(s) => {
                assert_eq!(s, "");
            }
            _ => panic!("Expected String value"),
        }
    }

    // =====================================================================
    // Tests for per_base helper functions
    // =====================================================================

    #[test]
    fn test_per_base_tags_to_reverse() {
        let tags = per_base::tags_to_reverse();
        for expected in [
            fgumi_sam::SamTag::CD_BASES,
            fgumi_sam::SamTag::CE_BASES,
            fgumi_sam::SamTag::AD_BASES,
            fgumi_sam::SamTag::AE_BASES,
            fgumi_sam::SamTag::BD_BASES,
            fgumi_sam::SamTag::BE_BASES,
            fgumi_sam::SamTag::AQ,
            fgumi_sam::SamTag::BQ,
        ] {
            assert!(tags.contains(&expected), "missing {expected}");
        }
    }

    #[test]
    fn test_per_base_tags_to_reverse_complement() {
        let tags = per_base::tags_to_reverse_complement();
        assert_eq!(tags, &[fgumi_sam::SamTag::AC, fgumi_sam::SamTag::BC_BASES]);
    }

    // =====================================================================
    // Tests for per_read tag constants
    // =====================================================================

    #[test]
    fn test_per_read_tag_constants() {
        assert_eq!(per_read::RAW_READ_COUNT, fgumi_sam::SamTag::CD);
        assert_eq!(per_read::MIN_RAW_READ_COUNT, fgumi_sam::SamTag::CM);
        assert_eq!(per_read::RAW_READ_ERROR_RATE, fgumi_sam::SamTag::CE);
        assert_eq!(per_read::AB_RAW_READ_COUNT, fgumi_sam::SamTag::AD);
        assert_eq!(per_read::BA_RAW_READ_COUNT, fgumi_sam::SamTag::BD);
        assert_eq!(per_read::AB_MIN_RAW_READ_COUNT, fgumi_sam::SamTag::AM);
        assert_eq!(per_read::BA_MIN_RAW_READ_COUNT, fgumi_sam::SamTag::BM);
        assert_eq!(per_read::AB_RAW_READ_ERROR_RATE, fgumi_sam::SamTag::AE);
        assert_eq!(per_read::BA_RAW_READ_ERROR_RATE, fgumi_sam::SamTag::BE);
    }

    #[test]
    fn test_per_base_tag_constants() {
        assert_eq!(per_base::RAW_READ_COUNT, fgumi_sam::SamTag::CD_BASES);
        assert_eq!(per_base::RAW_READ_ERRORS, fgumi_sam::SamTag::CE_BASES);
        assert_eq!(per_base::AB_RAW_READ_COUNT, fgumi_sam::SamTag::AD_BASES);
        assert_eq!(per_base::BA_RAW_READ_COUNT, fgumi_sam::SamTag::BD_BASES);
        assert_eq!(per_base::AB_RAW_READ_ERRORS, fgumi_sam::SamTag::AE_BASES);
        assert_eq!(per_base::BA_RAW_READ_ERRORS, fgumi_sam::SamTag::BE_BASES);
        assert_eq!(per_base::AB_CONSENSUS_BASES, fgumi_sam::SamTag::AC);
        assert_eq!(per_base::BA_CONSENSUS_BASES, fgumi_sam::SamTag::BC_BASES);
        assert_eq!(per_base::AB_CONSENSUS_QUALS, fgumi_sam::SamTag::AQ);
        assert_eq!(per_base::BA_CONSENSUS_QUALS, fgumi_sam::SamTag::BQ);
    }

    // =====================================================================
    // Tests for tag string constants
    // =====================================================================

    #[test]
    fn test_umi_tag_constants_match_sam_tag() {
        assert_eq!(UMI_BASES, fgumi_sam::SamTag::RX);
        assert_eq!(UMI_QUALS, fgumi_sam::SamTag::QX);
        assert_eq!(ORIGINAL_UMI_BASES, fgumi_sam::SamTag::OX);
        assert_eq!(ORIGINAL_UMI_QUALS, fgumi_sam::SamTag::BZ);
        assert_eq!(MOLECULAR_ID, fgumi_sam::SamTag::MI);
    }

    // =====================================================================
    // Test consensus detection with both simplex and duplex tags present
    // =====================================================================

    #[test]
    fn test_is_consensus_with_all_tags() {
        // Record with cD, aD, and bD is duplex, not simplex
        let rec = make_record_with_int_tags(&[(SamTag::CD, 10), (SamTag::AD, 5), (SamTag::BD, 3)]);

        assert!(!is_simplex_consensus(&rec));
        assert!(is_duplex_consensus(&rec));
        assert!(is_consensus(&rec));
    }

    #[test]
    fn test_is_not_duplex_with_only_one_strand() {
        // Record with only aD (no bD) is not duplex
        let rec = make_record_with_int_tags(&[(SamTag::AD, 5)]);

        assert!(!is_simplex_consensus(&rec));
        assert!(!is_duplex_consensus(&rec));
        assert!(!is_consensus(&rec));
    }
}
