use proc_macro::TokenStream;
use quote::{ToTokens, format_ident, quote};
use syn::{Lit, Meta};

/// Join all `#[doc = "..."]` attributes into a single trimmed string.
fn extract_doc_string(attrs: &[syn::Attribute]) -> String {
    attrs
        .iter()
        .filter_map(|attr| {
            if !attr.path().is_ident("doc") {
                return None;
            }
            if let Meta::NameValue(nv) = &attr.meta {
                if let syn::Expr::Lit(expr_lit) = &nv.value {
                    if let Lit::Str(lit) = &expr_lit.lit {
                        return Some(lit.value());
                    }
                }
            }
            None
        })
        .map(|l| l.trim().to_string())
        .collect::<Vec<_>>()
        .join(" ")
}

/// Attribute macro that passes through the original Options struct unchanged and
/// directly generates a `Multi{OriginalName}` struct with `--{prefix}::field-name`
/// CLI args, plus `validate()` and `From<OriginalName>` conversions.
///
/// Fields are classified into three categories:
/// - **Optional**: `Option<T>` fields are kept as `Option<T>` in the Multi struct.
/// - **Defaulted**: Non-`Option<T>` fields with `default_value_t` keep their type and default.
/// - **Required**: Non-`Option<T>` fields without `default_value_t` are wrapped in `Option<T>`
///   in the Multi struct. The generated `validate()` method checks they are `Some`.
///
/// Usage: `#[multi_options("prefix", "Help Heading")]`
///
/// # Panics
/// Panics if applied to a non-struct, a struct without named fields, or a struct
/// containing `#[command(flatten)]` (structs must be flat).
#[proc_macro_attribute]
pub fn multi_options(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = syn::parse::<MultiOptionsArgs>(attr).expect(
        "multi_options requires two string literal arguments: \
         #[multi_options(\"prefix\", \"heading\")]",
    );
    let prefix = &args.prefix;
    let heading = &args.heading;

    let input = syn::parse::<syn::ItemStruct>(item).expect("multi_options requires a struct");
    let struct_name = &input.ident;
    let multi_struct_name = format_ident!("Multi{}", struct_name);

    let fields = match &input.fields {
        syn::Fields::Named(named) => &named.named,
        _ => panic!("multi_options only supports structs with named fields"),
    };

    // Validate: no #[command(flatten)] fields (use structured meta parsing).
    for field in fields {
        for attr in &field.attrs {
            if !attr.path().is_ident("command") {
                continue;
            }
            if let Ok(nested) = attr.parse_args_with(
                syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated,
            ) {
                for meta in &nested {
                    assert!(
                        !meta.path().is_ident("flatten"),
                        "multi_options does not support #[command(flatten)] on field `{}`. \
                         Inline the flattened struct's fields directly.",
                        field.ident.as_ref().unwrap()
                    );
                }
            }
        }
    }

    let mut multi_field_tokens = Vec::new();
    let mut validate_field_tokens = Vec::new();
    let mut from_original_field_tokens = Vec::new();

    for field in fields {
        generate_field_tokens(
            field,
            struct_name,
            prefix,
            &mut multi_field_tokens,
            &mut validate_field_tokens,
            &mut from_original_field_tokens,
        );
    }

    let original = input.to_token_stream();

    let expanded = quote! {
        #original

        /// Prefixed options struct generated by `#[multi_options]` for the multi command.
        #[derive(clap::Args, Debug, Clone)]
        #[command(next_help_heading = #heading)]
        pub struct #multi_struct_name {
            #(#multi_field_tokens)*
        }

        impl #multi_struct_name {
            /// Validate required fields and convert to the original options struct.
            pub fn validate(self) -> anyhow::Result<#struct_name> {
                let opts = self;
                Ok(#struct_name {
                    #(#validate_field_tokens)*
                })
            }
        }

        impl From<#struct_name> for #multi_struct_name {
            fn from(opts: #struct_name) -> Self {
                Self {
                    #(#from_original_field_tokens)*
                }
            }
        }
    };

    TokenStream::from(expanded)
}

/// A single key=value (or bare key) item from `#[arg(...)]`, stored as raw tokens.
///
/// We cannot use `syn::Meta` because clap supports non-literal values such as
/// `num_args = 0..=1` (range expressions) and `value_parser = parse_bool` (bare
/// function paths without quotes).  This struct preserves the raw `TokenStream`
/// for each comma-separated item so that arbitrary clap attribute syntax is
/// forwarded to the generated Multi struct unchanged.
struct ArgItem {
    /// The identifier at the start of the item (e.g. `long`, `default_value_t`).
    name: String,
    /// The full token stream for this item (e.g. `num_args = 0..=1`).
    tokens: proc_macro2::TokenStream,
}

/// Parse the contents of a single `#[arg(...)]` attribute into [`ArgItem`]s.
///
/// Splits on top-level commas (commas not nested inside `()`, `[]`, or `{}`),
/// then extracts the leading identifier from each fragment.
fn parse_arg_items(attr: &syn::Attribute) -> Vec<ArgItem> {
    use proc_macro2::Delimiter;

    let tokens: proc_macro2::TokenStream = match &attr.meta {
        Meta::List(list) => list.tokens.clone(),
        _ => return Vec::new(),
    };

    // Split token stream by top-level commas.
    let mut items = Vec::new();
    let mut current = Vec::<proc_macro2::TokenTree>::new();
    for tt in tokens {
        match &tt {
            proc_macro2::TokenTree::Punct(p) if p.as_char() == ',' => {
                if !current.is_empty() {
                    let ts: proc_macro2::TokenStream = current.drain(..).collect();
                    items.push(ts);
                }
            }
            _ => current.push(tt),
        }
    }
    if !current.is_empty() {
        let ts: proc_macro2::TokenStream = current.drain(..).collect();
        items.push(ts);
    }

    // Extract the leading identifier from each item.
    items
        .into_iter()
        .map(|ts| {
            let mut iter = ts.clone().into_iter();
            match iter.next() {
                Some(proc_macro2::TokenTree::Ident(ident)) => {
                    ArgItem { name: ident.to_string(), tokens: ts }
                }
                // Handle group tokens (parenthesized metas like `value_enum`).
                Some(proc_macro2::TokenTree::Group(g)) if g.delimiter() == Delimiter::None => {
                    let mut inner = g.stream().into_iter();
                    if let Some(proc_macro2::TokenTree::Ident(ident)) = inner.next() {
                        ArgItem { name: ident.to_string(), tokens: ts }
                    } else {
                        ArgItem { name: String::new(), tokens: ts }
                    }
                }
                _ => ArgItem { name: String::new(), tokens: ts },
            }
        })
        .collect()
}

/// Parsed default-value classification for a field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DefaultKind {
    /// No default value attribute found.
    None,
    /// `default_value_t = <expr>` found — the Multi struct generates its own
    /// `default_value_t = StructName::default().field`.
    Typed,
    /// `default_value = "<string>"` found — already preserved in the attribute list,
    /// so the Multi struct must NOT add a `default_value_t`.
    String,
}

impl DefaultKind {
    fn has_default(self) -> bool {
        self != Self::None
    }
}

/// Parse all `#[arg(...)]` attributes from a field in a single pass.
///
/// Returns `(default_kind, preserved_arg_attrs)` where `default_kind` indicates
/// what kind of default was found, and `preserved_arg_attrs` contains
/// comma-prefixed token streams for all attributes that should be forwarded to
/// the Multi struct (everything except `long`, `short`, and `default_value_t`).
fn parse_arg_field_info(field: &syn::Field) -> (DefaultKind, Vec<proc_macro2::TokenStream>) {
    let mut default_kind = DefaultKind::None;
    let mut preserved = Vec::new();

    for attr in &field.attrs {
        if !attr.path().is_ident("arg") {
            continue;
        }
        for item in parse_arg_items(attr) {
            match item.name.as_str() {
                "default_value_t" => {
                    default_kind = DefaultKind::Typed;
                    // Replaced by the generated default in `generate_field_tokens`.
                }
                "default_value" => {
                    default_kind = DefaultKind::String;
                    // Preserve the string default so clap sees it in the Multi struct.
                    let ts = &item.tokens;
                    preserved.push(quote! { , #ts });
                }
                "long" | "short" => {
                    // Replaced by the generated `long = "prefix::field-name"`.
                }
                _ => {
                    let ts = &item.tokens;
                    preserved.push(quote! { , #ts });
                }
            }
        }
    }

    (default_kind, preserved)
}

/// Generate Multi-struct field, validate assignment, and `From<Original>` assignment
/// for a single field of the Options struct.
fn generate_field_tokens(
    field: &syn::Field,
    struct_name: &syn::Ident,
    prefix: &str,
    multi_field_tokens: &mut Vec<proc_macro2::TokenStream>,
    validate_field_tokens: &mut Vec<proc_macro2::TokenStream>,
    from_original_field_tokens: &mut Vec<proc_macro2::TokenStream>,
) {
    let field_ident = field.ident.as_ref().expect("named field");
    let field_type = &field.ty;
    let kebab_name = field_ident.to_string().replace('_', "-");
    let doc_comment = extract_doc_string(&field.attrs);
    let is_option = is_option_type(field_type);
    let (default_kind, preserved) = parse_arg_field_info(field);

    let long_name = format!("{prefix}::{kebab_name}");
    let prefixed_ident = format_ident!("{}_{}", prefix.replace('-', "_"), field_ident);

    let is_required = !is_option && !default_kind.has_default();

    if is_required {
        let required_doc = format!("{doc_comment} Required when {prefix} is selected.");
        let error_msg = format!("--{long_name} is required when {prefix} is selected");

        multi_field_tokens.push(quote! {
            #[doc = #required_doc]
            #[arg(long = #long_name #(#preserved)*)]
            pub #prefixed_ident: Option<#field_type>,
        });
        validate_field_tokens.push(quote! {
            #field_ident: opts.#prefixed_ident
                .ok_or_else(|| anyhow::anyhow!(#error_msg))?,
        });
        from_original_field_tokens.push(quote! {
            #prefixed_ident: Some(opts.#field_ident),
        });
    } else if is_option {
        multi_field_tokens.push(quote! {
            #[doc = #doc_comment]
            #[arg(long = #long_name #(#preserved)*)]
            pub #prefixed_ident: #field_type,
        });
        validate_field_tokens.push(quote! {
            #field_ident: opts.#prefixed_ident,
        });
        from_original_field_tokens.push(quote! {
            #prefixed_ident: opts.#field_ident,
        });
    } else {
        // For `default_value_t`, generate a typed default from `StructName::default().field`.
        // For `default_value` (string form), the default is already in `preserved`.
        let default_attr = if default_kind == DefaultKind::Typed {
            quote! { , default_value_t = #struct_name::default().#field_ident }
        } else {
            quote! {}
        };
        multi_field_tokens.push(quote! {
            #[doc = #doc_comment]
            #[arg(long = #long_name #default_attr #(#preserved)*)]
            pub #prefixed_ident: #field_type,
        });
        validate_field_tokens.push(quote! {
            #field_ident: opts.#prefixed_ident,
        });
        from_original_field_tokens.push(quote! {
            #prefixed_ident: opts.#field_ident,
        });
    }
}

/// Parsed arguments for the `#[multi_options("prefix", "heading")]` attribute.
struct MultiOptionsArgs {
    prefix: String,
    heading: String,
}

impl syn::parse::Parse for MultiOptionsArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let prefix_lit: syn::LitStr = input.parse()?;
        input.parse::<syn::Token![,]>()?;
        let heading_lit: syn::LitStr = input.parse()?;
        Ok(Self { prefix: prefix_lit.value(), heading: heading_lit.value() })
    }
}

/// Check if a type is `Option<T>`.
fn is_option_type(ty: &syn::Type) -> bool {
    if let syn::Type::Path(type_path) = ty {
        if let Some(segment) = type_path.path.segments.last() {
            return segment.ident == "Option";
        }
    }
    false
}
